//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClaimsDocsClient.proxyCDGroup {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Group", Namespace="http://schemas.datacontract.org/2004/07/ClaimsDocsBizLogic")]
    [System.SerializableAttribute()]
    public partial class Group : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DepartmentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GroupIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime IUDateTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DepartmentID {
            get {
                return this.DepartmentIDField;
            }
            set {
                if ((this.DepartmentIDField.Equals(value) != true)) {
                    this.DepartmentIDField = value;
                    this.RaisePropertyChanged("DepartmentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartmentName {
            get {
                return this.DepartmentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentNameField, value) != true)) {
                    this.DepartmentNameField = value;
                    this.RaisePropertyChanged("DepartmentName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GroupID {
            get {
                return this.GroupIDField;
            }
            set {
                if ((this.GroupIDField.Equals(value) != true)) {
                    this.GroupIDField = value;
                    this.RaisePropertyChanged("GroupID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupName {
            get {
                return this.GroupNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupNameField, value) != true)) {
                    this.GroupNameField = value;
                    this.RaisePropertyChanged("GroupName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime IUDateTime {
            get {
                return this.IUDateTimeField;
            }
            set {
                if ((this.IUDateTimeField.Equals(value) != true)) {
                    this.IUDateTimeField = value;
                    this.RaisePropertyChanged("IUDateTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="proxyCDGroup.ICDGroups")]
    public interface ICDGroups {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDGroups/GroupCreate", ReplyAction="http://tempuri.org/ICDGroups/GroupCreateResponse")]
        int GroupCreate(ClaimsDocsClient.proxyCDGroup.Group objGroup, string strConnectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDGroups/GroupRead", ReplyAction="http://tempuri.org/ICDGroups/GroupReadResponse")]
        ClaimsDocsClient.proxyCDGroup.Group GroupRead(ClaimsDocsClient.proxyCDGroup.Group objGroup, string strConnectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDGroups/GroupUpdate", ReplyAction="http://tempuri.org/ICDGroups/GroupUpdateResponse")]
        int GroupUpdate(ClaimsDocsClient.proxyCDGroup.Group objGroup, string strConnectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDGroups/GroupSearch", ReplyAction="http://tempuri.org/ICDGroups/GroupSearchResponse")]
        System.Collections.Generic.List<ClaimsDocsClient.proxyCDGroup.Group> GroupSearch(string strSQLString, string strConnectionString);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICDGroupsChannel : ClaimsDocsClient.proxyCDGroup.ICDGroups, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CDGroupsClient : System.ServiceModel.ClientBase<ClaimsDocsClient.proxyCDGroup.ICDGroups>, ClaimsDocsClient.proxyCDGroup.ICDGroups {
        
        public CDGroupsClient() {
        }
        
        public CDGroupsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CDGroupsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CDGroupsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CDGroupsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GroupCreate(ClaimsDocsClient.proxyCDGroup.Group objGroup, string strConnectionString) {
            return base.Channel.GroupCreate(objGroup, strConnectionString);
        }
        
        public ClaimsDocsClient.proxyCDGroup.Group GroupRead(ClaimsDocsClient.proxyCDGroup.Group objGroup, string strConnectionString) {
            return base.Channel.GroupRead(objGroup, strConnectionString);
        }
        
        public int GroupUpdate(ClaimsDocsClient.proxyCDGroup.Group objGroup, string strConnectionString) {
            return base.Channel.GroupUpdate(objGroup, strConnectionString);
        }
        
        public System.Collections.Generic.List<ClaimsDocsClient.proxyCDGroup.Group> GroupSearch(string strSQLString, string strConnectionString) {
            return base.Channel.GroupSearch(strSQLString, strConnectionString);
        }
    }
}
