//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClaimsDocsClient.proxyCDDocument2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Document", Namespace="http://schemas.datacontract.org/2004/07/ClaimsDocsBizLogic")]
    [System.SerializableAttribute()]
    public partial class Document : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdditionalDataRequiredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AttachedDocumentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ContactNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ContactTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CopyAgentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CopyAttorneyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CopyFinanceCoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CopyInsuredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CopyLienHolderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataMatxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DepartmentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DesignerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiaryAutoUpdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DiaryNumberOfDaysField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DocumentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EffectiveDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ExpirationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime IUDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageRightDocumentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageRightDocumentSectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageRightDrawerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImportToImageRightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InstanceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastModifiedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProgramCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProgramIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProofOfMailingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReviewField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StyleSheetNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TemplateNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ClaimsDocsClient.proxyCDDocument2.DocumentField> lisDocumentFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ClaimsDocsClient.proxyCDDocument2.DocumentGroup> listDocumentGroupField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((object.ReferenceEquals(this.ActiveField, value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdditionalDataRequired {
            get {
                return this.AdditionalDataRequiredField;
            }
            set {
                if ((object.ReferenceEquals(this.AdditionalDataRequiredField, value) != true)) {
                    this.AdditionalDataRequiredField = value;
                    this.RaisePropertyChanged("AdditionalDataRequired");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AttachedDocument {
            get {
                return this.AttachedDocumentField;
            }
            set {
                if ((object.ReferenceEquals(this.AttachedDocumentField, value) != true)) {
                    this.AttachedDocumentField = value;
                    this.RaisePropertyChanged("AttachedDocument");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ContactNo {
            get {
                return this.ContactNoField;
            }
            set {
                if ((this.ContactNoField.Equals(value) != true)) {
                    this.ContactNoField = value;
                    this.RaisePropertyChanged("ContactNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ContactType {
            get {
                return this.ContactTypeField;
            }
            set {
                if ((this.ContactTypeField.Equals(value) != true)) {
                    this.ContactTypeField = value;
                    this.RaisePropertyChanged("ContactType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CopyAgent {
            get {
                return this.CopyAgentField;
            }
            set {
                if ((object.ReferenceEquals(this.CopyAgentField, value) != true)) {
                    this.CopyAgentField = value;
                    this.RaisePropertyChanged("CopyAgent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CopyAttorney {
            get {
                return this.CopyAttorneyField;
            }
            set {
                if ((object.ReferenceEquals(this.CopyAttorneyField, value) != true)) {
                    this.CopyAttorneyField = value;
                    this.RaisePropertyChanged("CopyAttorney");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CopyFinanceCo {
            get {
                return this.CopyFinanceCoField;
            }
            set {
                if ((object.ReferenceEquals(this.CopyFinanceCoField, value) != true)) {
                    this.CopyFinanceCoField = value;
                    this.RaisePropertyChanged("CopyFinanceCo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CopyInsured {
            get {
                return this.CopyInsuredField;
            }
            set {
                if ((object.ReferenceEquals(this.CopyInsuredField, value) != true)) {
                    this.CopyInsuredField = value;
                    this.RaisePropertyChanged("CopyInsured");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CopyLienHolder {
            get {
                return this.CopyLienHolderField;
            }
            set {
                if ((object.ReferenceEquals(this.CopyLienHolderField, value) != true)) {
                    this.CopyLienHolderField = value;
                    this.RaisePropertyChanged("CopyLienHolder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataMatx {
            get {
                return this.DataMatxField;
            }
            set {
                if ((object.ReferenceEquals(this.DataMatxField, value) != true)) {
                    this.DataMatxField = value;
                    this.RaisePropertyChanged("DataMatx");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DepartmentID {
            get {
                return this.DepartmentIDField;
            }
            set {
                if ((this.DepartmentIDField.Equals(value) != true)) {
                    this.DepartmentIDField = value;
                    this.RaisePropertyChanged("DepartmentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DesignerID {
            get {
                return this.DesignerIDField;
            }
            set {
                if ((this.DesignerIDField.Equals(value) != true)) {
                    this.DesignerIDField = value;
                    this.RaisePropertyChanged("DesignerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiaryAutoUpdate {
            get {
                return this.DiaryAutoUpdateField;
            }
            set {
                if ((object.ReferenceEquals(this.DiaryAutoUpdateField, value) != true)) {
                    this.DiaryAutoUpdateField = value;
                    this.RaisePropertyChanged("DiaryAutoUpdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DiaryNumberOfDays {
            get {
                return this.DiaryNumberOfDaysField;
            }
            set {
                if ((this.DiaryNumberOfDaysField.Equals(value) != true)) {
                    this.DiaryNumberOfDaysField = value;
                    this.RaisePropertyChanged("DiaryNumberOfDays");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentCode {
            get {
                return this.DocumentCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentCodeField, value) != true)) {
                    this.DocumentCodeField = value;
                    this.RaisePropertyChanged("DocumentCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DocumentID {
            get {
                return this.DocumentIDField;
            }
            set {
                if ((this.DocumentIDField.Equals(value) != true)) {
                    this.DocumentIDField = value;
                    this.RaisePropertyChanged("DocumentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EffectiveDate {
            get {
                return this.EffectiveDateField;
            }
            set {
                if ((this.EffectiveDateField.Equals(value) != true)) {
                    this.EffectiveDateField = value;
                    this.RaisePropertyChanged("EffectiveDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ExpirationDate {
            get {
                return this.ExpirationDateField;
            }
            set {
                if ((this.ExpirationDateField.Equals(value) != true)) {
                    this.ExpirationDateField = value;
                    this.RaisePropertyChanged("ExpirationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime IUDateTime {
            get {
                return this.IUDateTimeField;
            }
            set {
                if ((this.IUDateTimeField.Equals(value) != true)) {
                    this.IUDateTimeField = value;
                    this.RaisePropertyChanged("IUDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageRightDocumentID {
            get {
                return this.ImageRightDocumentIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageRightDocumentIDField, value) != true)) {
                    this.ImageRightDocumentIDField = value;
                    this.RaisePropertyChanged("ImageRightDocumentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageRightDocumentSection {
            get {
                return this.ImageRightDocumentSectionField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageRightDocumentSectionField, value) != true)) {
                    this.ImageRightDocumentSectionField = value;
                    this.RaisePropertyChanged("ImageRightDocumentSection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageRightDrawer {
            get {
                return this.ImageRightDrawerField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageRightDrawerField, value) != true)) {
                    this.ImageRightDrawerField = value;
                    this.RaisePropertyChanged("ImageRightDrawer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImportToImageRight {
            get {
                return this.ImportToImageRightField;
            }
            set {
                if ((object.ReferenceEquals(this.ImportToImageRightField, value) != true)) {
                    this.ImportToImageRightField = value;
                    this.RaisePropertyChanged("ImportToImageRight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InstanceID {
            get {
                return this.InstanceIDField;
            }
            set {
                if ((object.ReferenceEquals(this.InstanceIDField, value) != true)) {
                    this.InstanceIDField = value;
                    this.RaisePropertyChanged("InstanceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastModified {
            get {
                return this.LastModifiedField;
            }
            set {
                if ((this.LastModifiedField.Equals(value) != true)) {
                    this.LastModifiedField = value;
                    this.RaisePropertyChanged("LastModified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProgramCode {
            get {
                return this.ProgramCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProgramCodeField, value) != true)) {
                    this.ProgramCodeField = value;
                    this.RaisePropertyChanged("ProgramCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProgramID {
            get {
                return this.ProgramIDField;
            }
            set {
                if ((this.ProgramIDField.Equals(value) != true)) {
                    this.ProgramIDField = value;
                    this.RaisePropertyChanged("ProgramID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProofOfMailing {
            get {
                return this.ProofOfMailingField;
            }
            set {
                if ((object.ReferenceEquals(this.ProofOfMailingField, value) != true)) {
                    this.ProofOfMailingField = value;
                    this.RaisePropertyChanged("ProofOfMailing");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Review {
            get {
                return this.ReviewField;
            }
            set {
                if ((object.ReferenceEquals(this.ReviewField, value) != true)) {
                    this.ReviewField = value;
                    this.RaisePropertyChanged("Review");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StyleSheetName {
            get {
                return this.StyleSheetNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StyleSheetNameField, value) != true)) {
                    this.StyleSheetNameField = value;
                    this.RaisePropertyChanged("StyleSheetName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TemplateName {
            get {
                return this.TemplateNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TemplateNameField, value) != true)) {
                    this.TemplateNameField = value;
                    this.RaisePropertyChanged("TemplateName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ClaimsDocsClient.proxyCDDocument2.DocumentField> lisDocumentField {
            get {
                return this.lisDocumentFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.lisDocumentFieldField, value) != true)) {
                    this.lisDocumentFieldField = value;
                    this.RaisePropertyChanged("lisDocumentField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ClaimsDocsClient.proxyCDDocument2.DocumentGroup> listDocumentGroup {
            get {
                return this.listDocumentGroupField;
            }
            set {
                if ((object.ReferenceEquals(this.listDocumentGroupField, value) != true)) {
                    this.listDocumentGroupField = value;
                    this.RaisePropertyChanged("listDocumentGroup");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentField", Namespace="http://schemas.datacontract.org/2004/07/ClaimsDocsBizLogic")]
    [System.SerializableAttribute()]
    public partial class DocumentField : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DocumentFieldIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DocumentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FieldDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FieldNameIsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FieldTypeIsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime IUDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IsFieldRequiredField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DocumentFieldID {
            get {
                return this.DocumentFieldIDField;
            }
            set {
                if ((this.DocumentFieldIDField.Equals(value) != true)) {
                    this.DocumentFieldIDField = value;
                    this.RaisePropertyChanged("DocumentFieldID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DocumentID {
            get {
                return this.DocumentIDField;
            }
            set {
                if ((this.DocumentIDField.Equals(value) != true)) {
                    this.DocumentIDField = value;
                    this.RaisePropertyChanged("DocumentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FieldDescription {
            get {
                return this.FieldDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldDescriptionField, value) != true)) {
                    this.FieldDescriptionField = value;
                    this.RaisePropertyChanged("FieldDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FieldNameIs {
            get {
                return this.FieldNameIsField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldNameIsField, value) != true)) {
                    this.FieldNameIsField = value;
                    this.RaisePropertyChanged("FieldNameIs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FieldTypeIs {
            get {
                return this.FieldTypeIsField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldTypeIsField, value) != true)) {
                    this.FieldTypeIsField = value;
                    this.RaisePropertyChanged("FieldTypeIs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime IUDateTime {
            get {
                return this.IUDateTimeField;
            }
            set {
                if ((this.IUDateTimeField.Equals(value) != true)) {
                    this.IUDateTimeField = value;
                    this.RaisePropertyChanged("IUDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IsFieldRequired {
            get {
                return this.IsFieldRequiredField;
            }
            set {
                if ((object.ReferenceEquals(this.IsFieldRequiredField, value) != true)) {
                    this.IsFieldRequiredField = value;
                    this.RaisePropertyChanged("IsFieldRequired");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentGroup", Namespace="http://schemas.datacontract.org/2004/07/ClaimsDocsBizLogic")]
    [System.SerializableAttribute()]
    public partial class DocumentGroup : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DocumentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GroupIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime IUDateTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DocumentID {
            get {
                return this.DocumentIDField;
            }
            set {
                if ((this.DocumentIDField.Equals(value) != true)) {
                    this.DocumentIDField = value;
                    this.RaisePropertyChanged("DocumentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GroupID {
            get {
                return this.GroupIDField;
            }
            set {
                if ((this.GroupIDField.Equals(value) != true)) {
                    this.GroupIDField = value;
                    this.RaisePropertyChanged("GroupID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime IUDateTime {
            get {
                return this.IUDateTimeField;
            }
            set {
                if ((this.IUDateTimeField.Equals(value) != true)) {
                    this.IUDateTimeField = value;
                    this.RaisePropertyChanged("IUDateTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentLog", Namespace="http://schemas.datacontract.org/2004/07/ClaimsDocsBizLogic")]
    [System.SerializableAttribute()]
    public partial class DocumentLog : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApprovalRequiredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ApproverIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaimNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateApprovedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateDeclinedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateGeneratedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateSubmittedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DeclinerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DocumentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GeneratedErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime IUDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InstanceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PolicyNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReasonDeclinedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SubmitterIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApprovalRequired {
            get {
                return this.ApprovalRequiredField;
            }
            set {
                if ((object.ReferenceEquals(this.ApprovalRequiredField, value) != true)) {
                    this.ApprovalRequiredField = value;
                    this.RaisePropertyChanged("ApprovalRequired");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ApproverID {
            get {
                return this.ApproverIDField;
            }
            set {
                if ((this.ApproverIDField.Equals(value) != true)) {
                    this.ApproverIDField = value;
                    this.RaisePropertyChanged("ApproverID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClaimNo {
            get {
                return this.ClaimNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaimNoField, value) != true)) {
                    this.ClaimNoField = value;
                    this.RaisePropertyChanged("ClaimNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateApproved {
            get {
                return this.DateApprovedField;
            }
            set {
                if ((this.DateApprovedField.Equals(value) != true)) {
                    this.DateApprovedField = value;
                    this.RaisePropertyChanged("DateApproved");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateDeclined {
            get {
                return this.DateDeclinedField;
            }
            set {
                if ((this.DateDeclinedField.Equals(value) != true)) {
                    this.DateDeclinedField = value;
                    this.RaisePropertyChanged("DateDeclined");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateGenerated {
            get {
                return this.DateGeneratedField;
            }
            set {
                if ((this.DateGeneratedField.Equals(value) != true)) {
                    this.DateGeneratedField = value;
                    this.RaisePropertyChanged("DateGenerated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateSubmitted {
            get {
                return this.DateSubmittedField;
            }
            set {
                if ((this.DateSubmittedField.Equals(value) != true)) {
                    this.DateSubmittedField = value;
                    this.RaisePropertyChanged("DateSubmitted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DeclinerID {
            get {
                return this.DeclinerIDField;
            }
            set {
                if ((this.DeclinerIDField.Equals(value) != true)) {
                    this.DeclinerIDField = value;
                    this.RaisePropertyChanged("DeclinerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DocumentID {
            get {
                return this.DocumentIDField;
            }
            set {
                if ((this.DocumentIDField.Equals(value) != true)) {
                    this.DocumentIDField = value;
                    this.RaisePropertyChanged("DocumentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GeneratedErrorCode {
            get {
                return this.GeneratedErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.GeneratedErrorCodeField, value) != true)) {
                    this.GeneratedErrorCodeField = value;
                    this.RaisePropertyChanged("GeneratedErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupName {
            get {
                return this.GroupNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupNameField, value) != true)) {
                    this.GroupNameField = value;
                    this.RaisePropertyChanged("GroupName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime IUDateTime {
            get {
                return this.IUDateTimeField;
            }
            set {
                if ((this.IUDateTimeField.Equals(value) != true)) {
                    this.IUDateTimeField = value;
                    this.RaisePropertyChanged("IUDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InstanceID {
            get {
                return this.InstanceIDField;
            }
            set {
                if ((object.ReferenceEquals(this.InstanceIDField, value) != true)) {
                    this.InstanceIDField = value;
                    this.RaisePropertyChanged("InstanceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PolicyNo {
            get {
                return this.PolicyNoField;
            }
            set {
                if ((object.ReferenceEquals(this.PolicyNoField, value) != true)) {
                    this.PolicyNoField = value;
                    this.RaisePropertyChanged("PolicyNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReasonDeclined {
            get {
                return this.ReasonDeclinedField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonDeclinedField, value) != true)) {
                    this.ReasonDeclinedField = value;
                    this.RaisePropertyChanged("ReasonDeclined");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SubmitterID {
            get {
                return this.SubmitterIDField;
            }
            set {
                if ((this.SubmitterIDField.Equals(value) != true)) {
                    this.SubmitterIDField = value;
                    this.RaisePropertyChanged("SubmitterID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentApprovalQueue", Namespace="http://schemas.datacontract.org/2004/07/ClaimsDocsBizLogic")]
    [System.SerializableAttribute()]
    public partial class DocumentApprovalQueue : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ApprovalQueueIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateSubmittedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DocumentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime IUDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InstanceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SubmitterIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ApprovalQueueID {
            get {
                return this.ApprovalQueueIDField;
            }
            set {
                if ((this.ApprovalQueueIDField.Equals(value) != true)) {
                    this.ApprovalQueueIDField = value;
                    this.RaisePropertyChanged("ApprovalQueueID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateSubmitted {
            get {
                return this.DateSubmittedField;
            }
            set {
                if ((this.DateSubmittedField.Equals(value) != true)) {
                    this.DateSubmittedField = value;
                    this.RaisePropertyChanged("DateSubmitted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DocumentID {
            get {
                return this.DocumentIDField;
            }
            set {
                if ((this.DocumentIDField.Equals(value) != true)) {
                    this.DocumentIDField = value;
                    this.RaisePropertyChanged("DocumentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime IUDateTime {
            get {
                return this.IUDateTimeField;
            }
            set {
                if ((this.IUDateTimeField.Equals(value) != true)) {
                    this.IUDateTimeField = value;
                    this.RaisePropertyChanged("IUDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InstanceID {
            get {
                return this.InstanceIDField;
            }
            set {
                if ((object.ReferenceEquals(this.InstanceIDField, value) != true)) {
                    this.InstanceIDField = value;
                    this.RaisePropertyChanged("InstanceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SubmitterID {
            get {
                return this.SubmitterIDField;
            }
            set {
                if ((this.SubmitterIDField.Equals(value) != true)) {
                    this.SubmitterIDField = value;
                    this.RaisePropertyChanged("SubmitterID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentsNeedingApproval", Namespace="http://schemas.datacontract.org/2004/07/ClaimsDocsBizLogic")]
    [System.SerializableAttribute()]
    public partial class DocumentsNeedingApproval : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ApprovalQueueIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateSubmittedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DocumentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InstanceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ApprovalQueueID {
            get {
                return this.ApprovalQueueIDField;
            }
            set {
                if ((this.ApprovalQueueIDField.Equals(value) != true)) {
                    this.ApprovalQueueIDField = value;
                    this.RaisePropertyChanged("ApprovalQueueID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateSubmitted {
            get {
                return this.DateSubmittedField;
            }
            set {
                if ((this.DateSubmittedField.Equals(value) != true)) {
                    this.DateSubmittedField = value;
                    this.RaisePropertyChanged("DateSubmitted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentCode {
            get {
                return this.DocumentCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentCodeField, value) != true)) {
                    this.DocumentCodeField = value;
                    this.RaisePropertyChanged("DocumentCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DocumentID {
            get {
                return this.DocumentIDField;
            }
            set {
                if ((this.DocumentIDField.Equals(value) != true)) {
                    this.DocumentIDField = value;
                    this.RaisePropertyChanged("DocumentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupName {
            get {
                return this.GroupNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupNameField, value) != true)) {
                    this.GroupNameField = value;
                    this.RaisePropertyChanged("GroupName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InstanceID {
            get {
                return this.InstanceIDField;
            }
            set {
                if ((object.ReferenceEquals(this.InstanceIDField, value) != true)) {
                    this.InstanceIDField = value;
                    this.RaisePropertyChanged("InstanceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="proxyCDDocument2.ICDDocument")]
    public interface ICDDocument {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDDocument/DocumentCreate", ReplyAction="http://tempuri.org/ICDDocument/DocumentCreateResponse")]
        int DocumentCreate(ClaimsDocsClient.proxyCDDocument2.Document objDocument, string strConnectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDDocument/DocumentRead", ReplyAction="http://tempuri.org/ICDDocument/DocumentReadResponse")]
        ClaimsDocsClient.proxyCDDocument2.Document DocumentRead(ClaimsDocsClient.proxyCDDocument2.Document objDocument, string strConnectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDDocument/DocumentUpdate", ReplyAction="http://tempuri.org/ICDDocument/DocumentUpdateResponse")]
        int DocumentUpdate(ClaimsDocsClient.proxyCDDocument2.Document objDocument, string strConnectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDDocument/DocumentSearch", ReplyAction="http://tempuri.org/ICDDocument/DocumentSearchResponse")]
        System.Collections.Generic.List<ClaimsDocsClient.proxyCDDocument2.Document> DocumentSearch(string strSQLString, string strConnectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDDocument/DocumentGroupSearch", ReplyAction="http://tempuri.org/ICDDocument/DocumentGroupSearchResponse")]
        System.Collections.Generic.List<ClaimsDocsClient.proxyCDDocument2.DocumentGroup> DocumentGroupSearch(string strSQLString, string strConnectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDDocument/DocumentGroupClear", ReplyAction="http://tempuri.org/ICDDocument/DocumentGroupClearResponse")]
        int DocumentGroupClear(ClaimsDocsClient.proxyCDDocument2.Document objDocument, string strConnectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDDocument/DocumentFieldSearch", ReplyAction="http://tempuri.org/ICDDocument/DocumentFieldSearchResponse")]
        System.Collections.Generic.List<ClaimsDocsClient.proxyCDDocument2.DocumentField> DocumentFieldSearch(string strSQLString, string strConnectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDDocument/DocumentFieldClear", ReplyAction="http://tempuri.org/ICDDocument/DocumentFieldClearResponse")]
        int DocumentFieldClear(ClaimsDocsClient.proxyCDDocument2.DocumentField objDocumentField, string strConnectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDDocument/DocumentFieldCreate", ReplyAction="http://tempuri.org/ICDDocument/DocumentFieldCreateResponse")]
        int DocumentFieldCreate(ClaimsDocsClient.proxyCDDocument2.DocumentField objDocumentField, string strConnectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDDocument/DocumentAdjusterListSearch", ReplyAction="http://tempuri.org/ICDDocument/DocumentAdjusterListSearchResponse")]
        System.Collections.Generic.List<ClaimsDocsClient.proxyCDDocument2.Document> DocumentAdjusterListSearch(string strSQLString, string strConnectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDDocument/DocumentLogCreate", ReplyAction="http://tempuri.org/ICDDocument/DocumentLogCreateResponse")]
        int DocumentLogCreate(ClaimsDocsClient.proxyCDDocument2.DocumentLog objDocumentLog, string strConnectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDDocument/DocumentLogUpdate", ReplyAction="http://tempuri.org/ICDDocument/DocumentLogUpdateResponse")]
        int DocumentLogUpdate(ClaimsDocsClient.proxyCDDocument2.DocumentLog objDocumentLog, string strConnectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDDocument/DocumentLogRead", ReplyAction="http://tempuri.org/ICDDocument/DocumentLogReadResponse")]
        ClaimsDocsClient.proxyCDDocument2.DocumentLog DocumentLogRead(string vchrInstanceID, string strConnectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDDocument/DocumentApprovalQueueCreate", ReplyAction="http://tempuri.org/ICDDocument/DocumentApprovalQueueCreateResponse")]
        int DocumentApprovalQueueCreate(ClaimsDocsClient.proxyCDDocument2.DocumentApprovalQueue objDocumentApprovalQueue, string strConnectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDDocument/DocumentApprovalQueueUpdate", ReplyAction="http://tempuri.org/ICDDocument/DocumentApprovalQueueUpdateResponse")]
        int DocumentApprovalQueueUpdate(ClaimsDocsClient.proxyCDDocument2.DocumentApprovalQueue objDocumentApprovalQueue, string strConnectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDDocument/DocumentDecline", ReplyAction="http://tempuri.org/ICDDocument/DocumentDeclineResponse")]
        int DocumentDecline(ClaimsDocsClient.proxyCDDocument2.DocumentLog objDocumentLog, string strConnectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDDocument/DocumentApprove", ReplyAction="http://tempuri.org/ICDDocument/DocumentApproveResponse")]
        int DocumentApprove(ClaimsDocsClient.proxyCDDocument2.DocumentLog objDocumentLog, string strConnectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDDocument/DocumentApprovalQueueReadALL", ReplyAction="http://tempuri.org/ICDDocument/DocumentApprovalQueueReadALLResponse")]
        System.Collections.Generic.List<ClaimsDocsClient.proxyCDDocument2.DocumentApprovalQueue> DocumentApprovalQueueReadALL(string strConnectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDDocument/DocumentApprovalQueueRead", ReplyAction="http://tempuri.org/ICDDocument/DocumentApprovalQueueReadResponse")]
        ClaimsDocsClient.proxyCDDocument2.DocumentApprovalQueue DocumentApprovalQueueRead(int intDocumentID, string strConnectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDDocument/DocumentsNeedingApprovalRead", ReplyAction="http://tempuri.org/ICDDocument/DocumentsNeedingApprovalReadResponse")]
        System.Collections.Generic.List<ClaimsDocsClient.proxyCDDocument2.DocumentsNeedingApproval> DocumentsNeedingApprovalRead(string strConnectionString);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICDDocumentChannel : ClaimsDocsClient.proxyCDDocument2.ICDDocument, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CDDocumentClient : System.ServiceModel.ClientBase<ClaimsDocsClient.proxyCDDocument2.ICDDocument>, ClaimsDocsClient.proxyCDDocument2.ICDDocument {
        
        public CDDocumentClient() {
        }
        
        public CDDocumentClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CDDocumentClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CDDocumentClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CDDocumentClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int DocumentCreate(ClaimsDocsClient.proxyCDDocument2.Document objDocument, string strConnectionString) {
            return base.Channel.DocumentCreate(objDocument, strConnectionString);
        }
        
        public ClaimsDocsClient.proxyCDDocument2.Document DocumentRead(ClaimsDocsClient.proxyCDDocument2.Document objDocument, string strConnectionString) {
            return base.Channel.DocumentRead(objDocument, strConnectionString);
        }
        
        public int DocumentUpdate(ClaimsDocsClient.proxyCDDocument2.Document objDocument, string strConnectionString) {
            return base.Channel.DocumentUpdate(objDocument, strConnectionString);
        }
        
        public System.Collections.Generic.List<ClaimsDocsClient.proxyCDDocument2.Document> DocumentSearch(string strSQLString, string strConnectionString) {
            return base.Channel.DocumentSearch(strSQLString, strConnectionString);
        }
        
        public System.Collections.Generic.List<ClaimsDocsClient.proxyCDDocument2.DocumentGroup> DocumentGroupSearch(string strSQLString, string strConnectionString) {
            return base.Channel.DocumentGroupSearch(strSQLString, strConnectionString);
        }
        
        public int DocumentGroupClear(ClaimsDocsClient.proxyCDDocument2.Document objDocument, string strConnectionString) {
            return base.Channel.DocumentGroupClear(objDocument, strConnectionString);
        }
        
        public System.Collections.Generic.List<ClaimsDocsClient.proxyCDDocument2.DocumentField> DocumentFieldSearch(string strSQLString, string strConnectionString) {
            return base.Channel.DocumentFieldSearch(strSQLString, strConnectionString);
        }
        
        public int DocumentFieldClear(ClaimsDocsClient.proxyCDDocument2.DocumentField objDocumentField, string strConnectionString) {
            return base.Channel.DocumentFieldClear(objDocumentField, strConnectionString);
        }
        
        public int DocumentFieldCreate(ClaimsDocsClient.proxyCDDocument2.DocumentField objDocumentField, string strConnectionString) {
            return base.Channel.DocumentFieldCreate(objDocumentField, strConnectionString);
        }
        
        public System.Collections.Generic.List<ClaimsDocsClient.proxyCDDocument2.Document> DocumentAdjusterListSearch(string strSQLString, string strConnectionString) {
            return base.Channel.DocumentAdjusterListSearch(strSQLString, strConnectionString);
        }
        
        public int DocumentLogCreate(ClaimsDocsClient.proxyCDDocument2.DocumentLog objDocumentLog, string strConnectionString) {
            return base.Channel.DocumentLogCreate(objDocumentLog, strConnectionString);
        }
        
        public int DocumentLogUpdate(ClaimsDocsClient.proxyCDDocument2.DocumentLog objDocumentLog, string strConnectionString) {
            return base.Channel.DocumentLogUpdate(objDocumentLog, strConnectionString);
        }
        
        public ClaimsDocsClient.proxyCDDocument2.DocumentLog DocumentLogRead(string vchrInstanceID, string strConnectionString) {
            return base.Channel.DocumentLogRead(vchrInstanceID, strConnectionString);
        }
        
        public int DocumentApprovalQueueCreate(ClaimsDocsClient.proxyCDDocument2.DocumentApprovalQueue objDocumentApprovalQueue, string strConnectionString) {
            return base.Channel.DocumentApprovalQueueCreate(objDocumentApprovalQueue, strConnectionString);
        }
        
        public int DocumentApprovalQueueUpdate(ClaimsDocsClient.proxyCDDocument2.DocumentApprovalQueue objDocumentApprovalQueue, string strConnectionString) {
            return base.Channel.DocumentApprovalQueueUpdate(objDocumentApprovalQueue, strConnectionString);
        }
        
        public int DocumentDecline(ClaimsDocsClient.proxyCDDocument2.DocumentLog objDocumentLog, string strConnectionString) {
            return base.Channel.DocumentDecline(objDocumentLog, strConnectionString);
        }
        
        public int DocumentApprove(ClaimsDocsClient.proxyCDDocument2.DocumentLog objDocumentLog, string strConnectionString) {
            return base.Channel.DocumentApprove(objDocumentLog, strConnectionString);
        }
        
        public System.Collections.Generic.List<ClaimsDocsClient.proxyCDDocument2.DocumentApprovalQueue> DocumentApprovalQueueReadALL(string strConnectionString) {
            return base.Channel.DocumentApprovalQueueReadALL(strConnectionString);
        }
        
        public ClaimsDocsClient.proxyCDDocument2.DocumentApprovalQueue DocumentApprovalQueueRead(int intDocumentID, string strConnectionString) {
            return base.Channel.DocumentApprovalQueueRead(intDocumentID, strConnectionString);
        }
        
        public System.Collections.Generic.List<ClaimsDocsClient.proxyCDDocument2.DocumentsNeedingApproval> DocumentsNeedingApprovalRead(string strConnectionString) {
            return base.Channel.DocumentsNeedingApprovalRead(strConnectionString);
        }
    }
}
