//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClaimsDocsClient.proxyCDDocumentGenerator {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="proxyCDDocumentGenerator.ICDDocumentGenerator")]
    public interface ICDDocumentGenerator {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDDocumentGenerator/GenerateDocument", ReplyAction="http://tempuri.org/ICDDocumentGenerator/GenerateDocumentResponse")]
        void GenerateDocument();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ICDDocumentGeneratorChannel : ClaimsDocsClient.proxyCDDocumentGenerator.ICDDocumentGenerator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class CDDocumentGeneratorClient : System.ServiceModel.ClientBase<ClaimsDocsClient.proxyCDDocumentGenerator.ICDDocumentGenerator>, ClaimsDocsClient.proxyCDDocumentGenerator.ICDDocumentGenerator {
        
        public CDDocumentGeneratorClient() {
        }
        
        public CDDocumentGeneratorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CDDocumentGeneratorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CDDocumentGeneratorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CDDocumentGeneratorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void GenerateDocument() {
            base.Channel.GenerateDocument();
        }
    }
}
