//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClaimsDocsClient.proxCDSupport {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClaimsDocsLog", Namespace="http://schemas.datacontract.org/2004/07/ClaimsDocsBizLogic")]
    [System.SerializableAttribute()]
    public partial class ClaimsDocsLog : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClaimsDocsLogIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionIsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime IUDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LogSourceTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LogTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogTypeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageIsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StackTraceIsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClaimsDocsLogID {
            get {
                return this.ClaimsDocsLogIDField;
            }
            set {
                if ((this.ClaimsDocsLogIDField.Equals(value) != true)) {
                    this.ClaimsDocsLogIDField = value;
                    this.RaisePropertyChanged("ClaimsDocsLogID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionIs {
            get {
                return this.ExceptionIsField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionIsField, value) != true)) {
                    this.ExceptionIsField = value;
                    this.RaisePropertyChanged("ExceptionIs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime IUDateTime {
            get {
                return this.IUDateTimeField;
            }
            set {
                if ((this.IUDateTimeField.Equals(value) != true)) {
                    this.IUDateTimeField = value;
                    this.RaisePropertyChanged("IUDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LogSourceTypeID {
            get {
                return this.LogSourceTypeIDField;
            }
            set {
                if ((this.LogSourceTypeIDField.Equals(value) != true)) {
                    this.LogSourceTypeIDField = value;
                    this.RaisePropertyChanged("LogSourceTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LogTypeID {
            get {
                return this.LogTypeIDField;
            }
            set {
                if ((this.LogTypeIDField.Equals(value) != true)) {
                    this.LogTypeIDField = value;
                    this.RaisePropertyChanged("LogTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogTypeName {
            get {
                return this.LogTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LogTypeNameField, value) != true)) {
                    this.LogTypeNameField = value;
                    this.RaisePropertyChanged("LogTypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageIs {
            get {
                return this.MessageIsField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageIsField, value) != true)) {
                    this.MessageIsField = value;
                    this.RaisePropertyChanged("MessageIs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SourceName {
            get {
                return this.SourceNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceNameField, value) != true)) {
                    this.SourceNameField = value;
                    this.RaisePropertyChanged("SourceName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTraceIs {
            get {
                return this.StackTraceIsField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceIsField, value) != true)) {
                    this.StackTraceIsField = value;
                    this.RaisePropertyChanged("StackTraceIs");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="proxCDSupport.ICDSupport")]
    public interface ICDSupport {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDSupport/ClaimsDocsLogCreate", ReplyAction="http://tempuri.org/ICDSupport/ClaimsDocsLogCreateResponse")]
        int ClaimsDocsLogCreate(ClaimsDocsClient.proxCDSupport.ClaimsDocsLog objClaimsDocsLog, string strConnectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDSupport/ClaimsDocsLogSearch", ReplyAction="http://tempuri.org/ICDSupport/ClaimsDocsLogSearchResponse")]
        ClaimsDocsClient.proxCDSupport.ClaimsDocsLog[] ClaimsDocsLogSearch(string strSQLString, string strConnectionString);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ICDSupportChannel : ClaimsDocsClient.proxCDSupport.ICDSupport, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class CDSupportClient : System.ServiceModel.ClientBase<ClaimsDocsClient.proxCDSupport.ICDSupport>, ClaimsDocsClient.proxCDSupport.ICDSupport {
        
        public CDSupportClient() {
        }
        
        public CDSupportClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CDSupportClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CDSupportClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CDSupportClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int ClaimsDocsLogCreate(ClaimsDocsClient.proxCDSupport.ClaimsDocsLog objClaimsDocsLog, string strConnectionString) {
            return base.Channel.ClaimsDocsLogCreate(objClaimsDocsLog, strConnectionString);
        }
        
        public ClaimsDocsClient.proxCDSupport.ClaimsDocsLog[] ClaimsDocsLogSearch(string strSQLString, string strConnectionString) {
            return base.Channel.ClaimsDocsLogSearch(strSQLString, strConnectionString);
        }
    }
}
