//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClaimsDocsClient.proxyCDProgram {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Program", Namespace="http://schemas.datacontract.org/2004/07/ClaimsDocsBizLogic")]
    [System.SerializableAttribute()]
    public partial class Program : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime IUDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProgramCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProgramIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime IUDateTime {
            get {
                return this.IUDateTimeField;
            }
            set {
                if ((this.IUDateTimeField.Equals(value) != true)) {
                    this.IUDateTimeField = value;
                    this.RaisePropertyChanged("IUDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProgramCode {
            get {
                return this.ProgramCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProgramCodeField, value) != true)) {
                    this.ProgramCodeField = value;
                    this.RaisePropertyChanged("ProgramCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProgramID {
            get {
                return this.ProgramIDField;
            }
            set {
                if ((this.ProgramIDField.Equals(value) != true)) {
                    this.ProgramIDField = value;
                    this.RaisePropertyChanged("ProgramID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="proxyCDProgram.ICDProgram")]
    public interface ICDProgram {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDProgram/ProgramCreate", ReplyAction="http://tempuri.org/ICDProgram/ProgramCreateResponse")]
        int ProgramCreate(ClaimsDocsClient.proxyCDProgram.Program objProgram, string strConnectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDProgram/ProgramRead", ReplyAction="http://tempuri.org/ICDProgram/ProgramReadResponse")]
        ClaimsDocsClient.proxyCDProgram.Program ProgramRead(ClaimsDocsClient.proxyCDProgram.Program objProgram, string strConnectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDProgram/ProgramUpdate", ReplyAction="http://tempuri.org/ICDProgram/ProgramUpdateResponse")]
        int ProgramUpdate(ClaimsDocsClient.proxyCDProgram.Program objProgram, string strConnectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDProgram/ProgramSearch", ReplyAction="http://tempuri.org/ICDProgram/ProgramSearchResponse")]
        System.Collections.Generic.List<ClaimsDocsClient.proxyCDProgram.Program> ProgramSearch(string strSQLString, string strConnectionString);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICDProgramChannel : ClaimsDocsClient.proxyCDProgram.ICDProgram, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CDProgramClient : System.ServiceModel.ClientBase<ClaimsDocsClient.proxyCDProgram.ICDProgram>, ClaimsDocsClient.proxyCDProgram.ICDProgram {
        
        public CDProgramClient() {
        }
        
        public CDProgramClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CDProgramClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CDProgramClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CDProgramClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int ProgramCreate(ClaimsDocsClient.proxyCDProgram.Program objProgram, string strConnectionString) {
            return base.Channel.ProgramCreate(objProgram, strConnectionString);
        }
        
        public ClaimsDocsClient.proxyCDProgram.Program ProgramRead(ClaimsDocsClient.proxyCDProgram.Program objProgram, string strConnectionString) {
            return base.Channel.ProgramRead(objProgram, strConnectionString);
        }
        
        public int ProgramUpdate(ClaimsDocsClient.proxyCDProgram.Program objProgram, string strConnectionString) {
            return base.Channel.ProgramUpdate(objProgram, strConnectionString);
        }
        
        public System.Collections.Generic.List<ClaimsDocsClient.proxyCDProgram.Program> ProgramSearch(string strSQLString, string strConnectionString) {
            return base.Channel.ProgramSearch(strSQLString, strConnectionString);
        }
    }
}
