//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClaimsDocsClient.proxyClaimsDocsGenerator {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocGenerationRequest", Namespace="http://schemas.datacontract.org/2004/07/ClaimsDocsBizLogic")]
    [System.SerializableAttribute()]
    public partial class DocGenerationRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaimNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ContactNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ContactTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DocumentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InstanceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PolicyNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClaimNumber {
            get {
                return this.ClaimNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaimNumberField, value) != true)) {
                    this.ClaimNumberField = value;
                    this.RaisePropertyChanged("ClaimNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ContactNumber {
            get {
                return this.ContactNumberField;
            }
            set {
                if ((this.ContactNumberField.Equals(value) != true)) {
                    this.ContactNumberField = value;
                    this.RaisePropertyChanged("ContactNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ContactType {
            get {
                return this.ContactTypeField;
            }
            set {
                if ((this.ContactTypeField.Equals(value) != true)) {
                    this.ContactTypeField = value;
                    this.RaisePropertyChanged("ContactType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DocumentID {
            get {
                return this.DocumentIDField;
            }
            set {
                if ((this.DocumentIDField.Equals(value) != true)) {
                    this.DocumentIDField = value;
                    this.RaisePropertyChanged("DocumentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InstanceID {
            get {
                return this.InstanceIDField;
            }
            set {
                if ((object.ReferenceEquals(this.InstanceIDField, value) != true)) {
                    this.InstanceIDField = value;
                    this.RaisePropertyChanged("InstanceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PolicyNumber {
            get {
                return this.PolicyNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PolicyNumberField, value) != true)) {
                    this.PolicyNumberField = value;
                    this.RaisePropertyChanged("PolicyNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIDField, value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PolicyInformation", Namespace="http://schemas.datacontract.org/2004/07/ClaimsDocsBizLogic")]
    [System.SerializableAttribute()]
    public partial class PolicyInformation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaimNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PolicyCancellationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PolicyEffectiveDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PolicyLastEndorsementDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PolicyLastExpirationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PolicyNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PolicyStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PolicyTermField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProgramCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClaimNumber {
            get {
                return this.ClaimNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaimNumberField, value) != true)) {
                    this.ClaimNumberField = value;
                    this.RaisePropertyChanged("ClaimNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Department {
            get {
                return this.DepartmentField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentField, value) != true)) {
                    this.DepartmentField = value;
                    this.RaisePropertyChanged("Department");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mode {
            get {
                return this.ModeField;
            }
            set {
                if ((object.ReferenceEquals(this.ModeField, value) != true)) {
                    this.ModeField = value;
                    this.RaisePropertyChanged("Mode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PolicyCancellationDate {
            get {
                return this.PolicyCancellationDateField;
            }
            set {
                if ((this.PolicyCancellationDateField.Equals(value) != true)) {
                    this.PolicyCancellationDateField = value;
                    this.RaisePropertyChanged("PolicyCancellationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PolicyEffectiveDate {
            get {
                return this.PolicyEffectiveDateField;
            }
            set {
                if ((this.PolicyEffectiveDateField.Equals(value) != true)) {
                    this.PolicyEffectiveDateField = value;
                    this.RaisePropertyChanged("PolicyEffectiveDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PolicyLastEndorsementDate {
            get {
                return this.PolicyLastEndorsementDateField;
            }
            set {
                if ((this.PolicyLastEndorsementDateField.Equals(value) != true)) {
                    this.PolicyLastEndorsementDateField = value;
                    this.RaisePropertyChanged("PolicyLastEndorsementDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PolicyLastExpirationDate {
            get {
                return this.PolicyLastExpirationDateField;
            }
            set {
                if ((this.PolicyLastExpirationDateField.Equals(value) != true)) {
                    this.PolicyLastExpirationDateField = value;
                    this.RaisePropertyChanged("PolicyLastExpirationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PolicyNumber {
            get {
                return this.PolicyNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PolicyNumberField, value) != true)) {
                    this.PolicyNumberField = value;
                    this.RaisePropertyChanged("PolicyNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PolicyStatus {
            get {
                return this.PolicyStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.PolicyStatusField, value) != true)) {
                    this.PolicyStatusField = value;
                    this.RaisePropertyChanged("PolicyStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PolicyTerm {
            get {
                return this.PolicyTermField;
            }
            set {
                if ((object.ReferenceEquals(this.PolicyTermField, value) != true)) {
                    this.PolicyTermField = value;
                    this.RaisePropertyChanged("PolicyTerm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProgramCode {
            get {
                return this.ProgramCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProgramCodeField, value) != true)) {
                    this.ProgramCodeField = value;
                    this.RaisePropertyChanged("ProgramCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddresseeInformation", Namespace="http://schemas.datacontract.org/2004/07/ClaimsDocsBizLogic")]
    [System.SerializableAttribute()]
    public partial class AddresseeInformation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine1 {
            get {
                return this.AddressLine1Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine1Field, value) != true)) {
                    this.AddressLine1Field = value;
                    this.RaisePropertyChanged("AddressLine1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine2 {
            get {
                return this.AddressLine2Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine2Field, value) != true)) {
                    this.AddressLine2Field = value;
                    this.RaisePropertyChanged("AddressLine2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine3 {
            get {
                return this.AddressLine3Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine3Field, value) != true)) {
                    this.AddressLine3Field = value;
                    this.RaisePropertyChanged("AddressLine3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMail {
            get {
                return this.EMailField;
            }
            set {
                if ((object.ReferenceEquals(this.EMailField, value) != true)) {
                    this.EMailField = value;
                    this.RaisePropertyChanged("EMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fax {
            get {
                return this.FaxField;
            }
            set {
                if ((object.ReferenceEquals(this.FaxField, value) != true)) {
                    this.FaxField = value;
                    this.RaisePropertyChanged("Fax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Coverage", Namespace="http://schemas.datacontract.org/2004/07/ClaimsDocsBizLogic")]
    [System.SerializableAttribute()]
    public partial class Coverage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccidentalDeathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArbitrationAgreementWaiverField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AutoClubField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BillingServiceChargesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BodilyInjuryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrokersFeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CIGAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CollisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CollissionDeductibleWaiverField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CombinedFPBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CombinedSingleLimitsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComprehensiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExpenseConstantField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtraMedicalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FilingFeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FuneralField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IncomeLossField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MedicalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PersonalFamilyProtectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PolicyFeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PropertyDamageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RentalReimbursementField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SpecialEquipmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TowingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnInsuredMotoristStackedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnInsuredMotoristUnStackedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnderInsuredMotoristStackedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnderInsuredMotoristUnStackedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UninsuredMotoristBIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UninsuredMotoristPDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccidentalDeath {
            get {
                return this.AccidentalDeathField;
            }
            set {
                if ((object.ReferenceEquals(this.AccidentalDeathField, value) != true)) {
                    this.AccidentalDeathField = value;
                    this.RaisePropertyChanged("AccidentalDeath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ArbitrationAgreementWaiver {
            get {
                return this.ArbitrationAgreementWaiverField;
            }
            set {
                if ((object.ReferenceEquals(this.ArbitrationAgreementWaiverField, value) != true)) {
                    this.ArbitrationAgreementWaiverField = value;
                    this.RaisePropertyChanged("ArbitrationAgreementWaiver");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AutoClub {
            get {
                return this.AutoClubField;
            }
            set {
                if ((object.ReferenceEquals(this.AutoClubField, value) != true)) {
                    this.AutoClubField = value;
                    this.RaisePropertyChanged("AutoClub");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillingServiceCharges {
            get {
                return this.BillingServiceChargesField;
            }
            set {
                if ((object.ReferenceEquals(this.BillingServiceChargesField, value) != true)) {
                    this.BillingServiceChargesField = value;
                    this.RaisePropertyChanged("BillingServiceCharges");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BodilyInjury {
            get {
                return this.BodilyInjuryField;
            }
            set {
                if ((object.ReferenceEquals(this.BodilyInjuryField, value) != true)) {
                    this.BodilyInjuryField = value;
                    this.RaisePropertyChanged("BodilyInjury");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BrokersFee {
            get {
                return this.BrokersFeeField;
            }
            set {
                if ((object.ReferenceEquals(this.BrokersFeeField, value) != true)) {
                    this.BrokersFeeField = value;
                    this.RaisePropertyChanged("BrokersFee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CIGA {
            get {
                return this.CIGAField;
            }
            set {
                if ((object.ReferenceEquals(this.CIGAField, value) != true)) {
                    this.CIGAField = value;
                    this.RaisePropertyChanged("CIGA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Collision {
            get {
                return this.CollisionField;
            }
            set {
                if ((object.ReferenceEquals(this.CollisionField, value) != true)) {
                    this.CollisionField = value;
                    this.RaisePropertyChanged("Collision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CollissionDeductibleWaiver {
            get {
                return this.CollissionDeductibleWaiverField;
            }
            set {
                if ((object.ReferenceEquals(this.CollissionDeductibleWaiverField, value) != true)) {
                    this.CollissionDeductibleWaiverField = value;
                    this.RaisePropertyChanged("CollissionDeductibleWaiver");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CombinedFPB {
            get {
                return this.CombinedFPBField;
            }
            set {
                if ((object.ReferenceEquals(this.CombinedFPBField, value) != true)) {
                    this.CombinedFPBField = value;
                    this.RaisePropertyChanged("CombinedFPB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CombinedSingleLimits {
            get {
                return this.CombinedSingleLimitsField;
            }
            set {
                if ((object.ReferenceEquals(this.CombinedSingleLimitsField, value) != true)) {
                    this.CombinedSingleLimitsField = value;
                    this.RaisePropertyChanged("CombinedSingleLimits");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comprehensive {
            get {
                return this.ComprehensiveField;
            }
            set {
                if ((object.ReferenceEquals(this.ComprehensiveField, value) != true)) {
                    this.ComprehensiveField = value;
                    this.RaisePropertyChanged("Comprehensive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExpenseConstant {
            get {
                return this.ExpenseConstantField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpenseConstantField, value) != true)) {
                    this.ExpenseConstantField = value;
                    this.RaisePropertyChanged("ExpenseConstant");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExtraMedical {
            get {
                return this.ExtraMedicalField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtraMedicalField, value) != true)) {
                    this.ExtraMedicalField = value;
                    this.RaisePropertyChanged("ExtraMedical");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FilingFee {
            get {
                return this.FilingFeeField;
            }
            set {
                if ((object.ReferenceEquals(this.FilingFeeField, value) != true)) {
                    this.FilingFeeField = value;
                    this.RaisePropertyChanged("FilingFee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Funeral {
            get {
                return this.FuneralField;
            }
            set {
                if ((object.ReferenceEquals(this.FuneralField, value) != true)) {
                    this.FuneralField = value;
                    this.RaisePropertyChanged("Funeral");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IncomeLoss {
            get {
                return this.IncomeLossField;
            }
            set {
                if ((object.ReferenceEquals(this.IncomeLossField, value) != true)) {
                    this.IncomeLossField = value;
                    this.RaisePropertyChanged("IncomeLoss");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Medical {
            get {
                return this.MedicalField;
            }
            set {
                if ((object.ReferenceEquals(this.MedicalField, value) != true)) {
                    this.MedicalField = value;
                    this.RaisePropertyChanged("Medical");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonalFamilyProtection {
            get {
                return this.PersonalFamilyProtectionField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonalFamilyProtectionField, value) != true)) {
                    this.PersonalFamilyProtectionField = value;
                    this.RaisePropertyChanged("PersonalFamilyProtection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PolicyFee {
            get {
                return this.PolicyFeeField;
            }
            set {
                if ((object.ReferenceEquals(this.PolicyFeeField, value) != true)) {
                    this.PolicyFeeField = value;
                    this.RaisePropertyChanged("PolicyFee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PropertyDamage {
            get {
                return this.PropertyDamageField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertyDamageField, value) != true)) {
                    this.PropertyDamageField = value;
                    this.RaisePropertyChanged("PropertyDamage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RentalReimbursement {
            get {
                return this.RentalReimbursementField;
            }
            set {
                if ((object.ReferenceEquals(this.RentalReimbursementField, value) != true)) {
                    this.RentalReimbursementField = value;
                    this.RaisePropertyChanged("RentalReimbursement");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SpecialEquipment {
            get {
                return this.SpecialEquipmentField;
            }
            set {
                if ((object.ReferenceEquals(this.SpecialEquipmentField, value) != true)) {
                    this.SpecialEquipmentField = value;
                    this.RaisePropertyChanged("SpecialEquipment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Towing {
            get {
                return this.TowingField;
            }
            set {
                if ((object.ReferenceEquals(this.TowingField, value) != true)) {
                    this.TowingField = value;
                    this.RaisePropertyChanged("Towing");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnInsuredMotoristStacked {
            get {
                return this.UnInsuredMotoristStackedField;
            }
            set {
                if ((object.ReferenceEquals(this.UnInsuredMotoristStackedField, value) != true)) {
                    this.UnInsuredMotoristStackedField = value;
                    this.RaisePropertyChanged("UnInsuredMotoristStacked");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnInsuredMotoristUnStacked {
            get {
                return this.UnInsuredMotoristUnStackedField;
            }
            set {
                if ((object.ReferenceEquals(this.UnInsuredMotoristUnStackedField, value) != true)) {
                    this.UnInsuredMotoristUnStackedField = value;
                    this.RaisePropertyChanged("UnInsuredMotoristUnStacked");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnderInsuredMotoristStacked {
            get {
                return this.UnderInsuredMotoristStackedField;
            }
            set {
                if ((object.ReferenceEquals(this.UnderInsuredMotoristStackedField, value) != true)) {
                    this.UnderInsuredMotoristStackedField = value;
                    this.RaisePropertyChanged("UnderInsuredMotoristStacked");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnderInsuredMotoristUnStacked {
            get {
                return this.UnderInsuredMotoristUnStackedField;
            }
            set {
                if ((object.ReferenceEquals(this.UnderInsuredMotoristUnStackedField, value) != true)) {
                    this.UnderInsuredMotoristUnStackedField = value;
                    this.RaisePropertyChanged("UnderInsuredMotoristUnStacked");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UninsuredMotoristBI {
            get {
                return this.UninsuredMotoristBIField;
            }
            set {
                if ((object.ReferenceEquals(this.UninsuredMotoristBIField, value) != true)) {
                    this.UninsuredMotoristBIField = value;
                    this.RaisePropertyChanged("UninsuredMotoristBI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UninsuredMotoristPD {
            get {
                return this.UninsuredMotoristPDField;
            }
            set {
                if ((object.ReferenceEquals(this.UninsuredMotoristPDField, value) != true)) {
                    this.UninsuredMotoristPDField = value;
                    this.RaisePropertyChanged("UninsuredMotoristPD");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="proxyClaimsDocsGenerator.IClaimsDocsGenerator")]
    public interface IClaimsDocsGenerator {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClaimsDocsGenerator/ClaimsDocsGenerateXML", ReplyAction="http://tempuri.org/IClaimsDocsGenerator/ClaimsDocsGenerateXMLResponse")]
        string ClaimsDocsGenerateXML(ClaimsDocsClient.proxyClaimsDocsGenerator.DocGenerationRequest objDocumentGenerationRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClaimsDocsGenerator/PolicyInformationGet", ReplyAction="http://tempuri.org/IClaimsDocsGenerator/PolicyInformationGetResponse")]
        ClaimsDocsClient.proxyClaimsDocsGenerator.PolicyInformation PolicyInformationGet(ClaimsDocsClient.proxyClaimsDocsGenerator.DocGenerationRequest objDocumentGenerationRequest, string strConnectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClaimsDocsGenerator/AddresseeInformationGet", ReplyAction="http://tempuri.org/IClaimsDocsGenerator/AddresseeInformationGetResponse")]
        ClaimsDocsClient.proxyClaimsDocsGenerator.AddresseeInformation AddresseeInformationGet(ClaimsDocsClient.proxyClaimsDocsGenerator.DocGenerationRequest objDocumentGenerationRequest, string strAMSDBConnectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClaimsDocsGenerator/CoverageInformationGet", ReplyAction="http://tempuri.org/IClaimsDocsGenerator/CoverageInformationGetResponse")]
        ClaimsDocsClient.proxyClaimsDocsGenerator.Coverage CoverageInformationGet(ClaimsDocsClient.proxyClaimsDocsGenerator.DocGenerationRequest objDocumentGenerationRequest, string strClaimsDBConnectionString);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IClaimsDocsGeneratorChannel : ClaimsDocsClient.proxyClaimsDocsGenerator.IClaimsDocsGenerator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ClaimsDocsGeneratorClient : System.ServiceModel.ClientBase<ClaimsDocsClient.proxyClaimsDocsGenerator.IClaimsDocsGenerator>, ClaimsDocsClient.proxyClaimsDocsGenerator.IClaimsDocsGenerator {
        
        public ClaimsDocsGeneratorClient() {
        }
        
        public ClaimsDocsGeneratorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClaimsDocsGeneratorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClaimsDocsGeneratorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClaimsDocsGeneratorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ClaimsDocsGenerateXML(ClaimsDocsClient.proxyClaimsDocsGenerator.DocGenerationRequest objDocumentGenerationRequest) {
            return base.Channel.ClaimsDocsGenerateXML(objDocumentGenerationRequest);
        }
        
        public ClaimsDocsClient.proxyClaimsDocsGenerator.PolicyInformation PolicyInformationGet(ClaimsDocsClient.proxyClaimsDocsGenerator.DocGenerationRequest objDocumentGenerationRequest, string strConnectionString) {
            return base.Channel.PolicyInformationGet(objDocumentGenerationRequest, strConnectionString);
        }
        
        public ClaimsDocsClient.proxyClaimsDocsGenerator.AddresseeInformation AddresseeInformationGet(ClaimsDocsClient.proxyClaimsDocsGenerator.DocGenerationRequest objDocumentGenerationRequest, string strAMSDBConnectionString) {
            return base.Channel.AddresseeInformationGet(objDocumentGenerationRequest, strAMSDBConnectionString);
        }
        
        public ClaimsDocsClient.proxyClaimsDocsGenerator.Coverage CoverageInformationGet(ClaimsDocsClient.proxyClaimsDocsGenerator.DocGenerationRequest objDocumentGenerationRequest, string strClaimsDBConnectionString) {
            return base.Channel.CoverageInformationGet(objDocumentGenerationRequest, strClaimsDBConnectionString);
        }
    }
}
