//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClaimsDocsClient.proxClaimsDocsGenerator {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Document", Namespace="http://schemas.datacontract.org/2004/07/ClaimsDocsBizLogic")]
    [System.SerializableAttribute()]
    public partial class Document : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdditionalDataRequiredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AttachedDocumentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CopyAgentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CopyAttorneyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CopyFinanceCoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CopyInsuredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CopyLienHolderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataMatxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DepartmentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DesignerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiaryAutoUpdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DiaryNumberOfDaysField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DocumentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EffectiveDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ExpirationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime IUDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageRightDocumentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageRightDocumentSectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageRightDrawerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImportToImageRightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InstanceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastModifiedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProgramCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProgramIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProofOfMailingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReviewField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StyleSheetNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TemplateNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ClaimsDocsClient.proxClaimsDocsGenerator.DocumentField> lisDocumentFieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ClaimsDocsClient.proxClaimsDocsGenerator.DocumentGroup> listDocumentGroupField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((object.ReferenceEquals(this.ActiveField, value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdditionalDataRequired {
            get {
                return this.AdditionalDataRequiredField;
            }
            set {
                if ((object.ReferenceEquals(this.AdditionalDataRequiredField, value) != true)) {
                    this.AdditionalDataRequiredField = value;
                    this.RaisePropertyChanged("AdditionalDataRequired");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AttachedDocument {
            get {
                return this.AttachedDocumentField;
            }
            set {
                if ((object.ReferenceEquals(this.AttachedDocumentField, value) != true)) {
                    this.AttachedDocumentField = value;
                    this.RaisePropertyChanged("AttachedDocument");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CopyAgent {
            get {
                return this.CopyAgentField;
            }
            set {
                if ((object.ReferenceEquals(this.CopyAgentField, value) != true)) {
                    this.CopyAgentField = value;
                    this.RaisePropertyChanged("CopyAgent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CopyAttorney {
            get {
                return this.CopyAttorneyField;
            }
            set {
                if ((object.ReferenceEquals(this.CopyAttorneyField, value) != true)) {
                    this.CopyAttorneyField = value;
                    this.RaisePropertyChanged("CopyAttorney");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CopyFinanceCo {
            get {
                return this.CopyFinanceCoField;
            }
            set {
                if ((object.ReferenceEquals(this.CopyFinanceCoField, value) != true)) {
                    this.CopyFinanceCoField = value;
                    this.RaisePropertyChanged("CopyFinanceCo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CopyInsured {
            get {
                return this.CopyInsuredField;
            }
            set {
                if ((object.ReferenceEquals(this.CopyInsuredField, value) != true)) {
                    this.CopyInsuredField = value;
                    this.RaisePropertyChanged("CopyInsured");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CopyLienHolder {
            get {
                return this.CopyLienHolderField;
            }
            set {
                if ((object.ReferenceEquals(this.CopyLienHolderField, value) != true)) {
                    this.CopyLienHolderField = value;
                    this.RaisePropertyChanged("CopyLienHolder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataMatx {
            get {
                return this.DataMatxField;
            }
            set {
                if ((object.ReferenceEquals(this.DataMatxField, value) != true)) {
                    this.DataMatxField = value;
                    this.RaisePropertyChanged("DataMatx");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DepartmentID {
            get {
                return this.DepartmentIDField;
            }
            set {
                if ((this.DepartmentIDField.Equals(value) != true)) {
                    this.DepartmentIDField = value;
                    this.RaisePropertyChanged("DepartmentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DesignerID {
            get {
                return this.DesignerIDField;
            }
            set {
                if ((this.DesignerIDField.Equals(value) != true)) {
                    this.DesignerIDField = value;
                    this.RaisePropertyChanged("DesignerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiaryAutoUpdate {
            get {
                return this.DiaryAutoUpdateField;
            }
            set {
                if ((object.ReferenceEquals(this.DiaryAutoUpdateField, value) != true)) {
                    this.DiaryAutoUpdateField = value;
                    this.RaisePropertyChanged("DiaryAutoUpdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DiaryNumberOfDays {
            get {
                return this.DiaryNumberOfDaysField;
            }
            set {
                if ((this.DiaryNumberOfDaysField.Equals(value) != true)) {
                    this.DiaryNumberOfDaysField = value;
                    this.RaisePropertyChanged("DiaryNumberOfDays");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentCode {
            get {
                return this.DocumentCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentCodeField, value) != true)) {
                    this.DocumentCodeField = value;
                    this.RaisePropertyChanged("DocumentCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DocumentID {
            get {
                return this.DocumentIDField;
            }
            set {
                if ((this.DocumentIDField.Equals(value) != true)) {
                    this.DocumentIDField = value;
                    this.RaisePropertyChanged("DocumentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EffectiveDate {
            get {
                return this.EffectiveDateField;
            }
            set {
                if ((this.EffectiveDateField.Equals(value) != true)) {
                    this.EffectiveDateField = value;
                    this.RaisePropertyChanged("EffectiveDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ExpirationDate {
            get {
                return this.ExpirationDateField;
            }
            set {
                if ((this.ExpirationDateField.Equals(value) != true)) {
                    this.ExpirationDateField = value;
                    this.RaisePropertyChanged("ExpirationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime IUDateTime {
            get {
                return this.IUDateTimeField;
            }
            set {
                if ((this.IUDateTimeField.Equals(value) != true)) {
                    this.IUDateTimeField = value;
                    this.RaisePropertyChanged("IUDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageRightDocumentID {
            get {
                return this.ImageRightDocumentIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageRightDocumentIDField, value) != true)) {
                    this.ImageRightDocumentIDField = value;
                    this.RaisePropertyChanged("ImageRightDocumentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageRightDocumentSection {
            get {
                return this.ImageRightDocumentSectionField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageRightDocumentSectionField, value) != true)) {
                    this.ImageRightDocumentSectionField = value;
                    this.RaisePropertyChanged("ImageRightDocumentSection");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageRightDrawer {
            get {
                return this.ImageRightDrawerField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageRightDrawerField, value) != true)) {
                    this.ImageRightDrawerField = value;
                    this.RaisePropertyChanged("ImageRightDrawer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImportToImageRight {
            get {
                return this.ImportToImageRightField;
            }
            set {
                if ((object.ReferenceEquals(this.ImportToImageRightField, value) != true)) {
                    this.ImportToImageRightField = value;
                    this.RaisePropertyChanged("ImportToImageRight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InstanceID {
            get {
                return this.InstanceIDField;
            }
            set {
                if ((object.ReferenceEquals(this.InstanceIDField, value) != true)) {
                    this.InstanceIDField = value;
                    this.RaisePropertyChanged("InstanceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastModified {
            get {
                return this.LastModifiedField;
            }
            set {
                if ((this.LastModifiedField.Equals(value) != true)) {
                    this.LastModifiedField = value;
                    this.RaisePropertyChanged("LastModified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProgramCode {
            get {
                return this.ProgramCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProgramCodeField, value) != true)) {
                    this.ProgramCodeField = value;
                    this.RaisePropertyChanged("ProgramCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProgramID {
            get {
                return this.ProgramIDField;
            }
            set {
                if ((this.ProgramIDField.Equals(value) != true)) {
                    this.ProgramIDField = value;
                    this.RaisePropertyChanged("ProgramID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProofOfMailing {
            get {
                return this.ProofOfMailingField;
            }
            set {
                if ((object.ReferenceEquals(this.ProofOfMailingField, value) != true)) {
                    this.ProofOfMailingField = value;
                    this.RaisePropertyChanged("ProofOfMailing");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Review {
            get {
                return this.ReviewField;
            }
            set {
                if ((object.ReferenceEquals(this.ReviewField, value) != true)) {
                    this.ReviewField = value;
                    this.RaisePropertyChanged("Review");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StyleSheetName {
            get {
                return this.StyleSheetNameField;
            }
            set {
                if ((object.ReferenceEquals(this.StyleSheetNameField, value) != true)) {
                    this.StyleSheetNameField = value;
                    this.RaisePropertyChanged("StyleSheetName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TemplateName {
            get {
                return this.TemplateNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TemplateNameField, value) != true)) {
                    this.TemplateNameField = value;
                    this.RaisePropertyChanged("TemplateName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ClaimsDocsClient.proxClaimsDocsGenerator.DocumentField> lisDocumentField {
            get {
                return this.lisDocumentFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.lisDocumentFieldField, value) != true)) {
                    this.lisDocumentFieldField = value;
                    this.RaisePropertyChanged("lisDocumentField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ClaimsDocsClient.proxClaimsDocsGenerator.DocumentGroup> listDocumentGroup {
            get {
                return this.listDocumentGroupField;
            }
            set {
                if ((object.ReferenceEquals(this.listDocumentGroupField, value) != true)) {
                    this.listDocumentGroupField = value;
                    this.RaisePropertyChanged("listDocumentGroup");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentField", Namespace="http://schemas.datacontract.org/2004/07/ClaimsDocsBizLogic")]
    [System.SerializableAttribute()]
    public partial class DocumentField : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DocumentFieldIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DocumentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FieldDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FieldNameIsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FieldTypeIsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime IUDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IsFieldRequiredField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DocumentFieldID {
            get {
                return this.DocumentFieldIDField;
            }
            set {
                if ((this.DocumentFieldIDField.Equals(value) != true)) {
                    this.DocumentFieldIDField = value;
                    this.RaisePropertyChanged("DocumentFieldID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DocumentID {
            get {
                return this.DocumentIDField;
            }
            set {
                if ((this.DocumentIDField.Equals(value) != true)) {
                    this.DocumentIDField = value;
                    this.RaisePropertyChanged("DocumentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FieldDescription {
            get {
                return this.FieldDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldDescriptionField, value) != true)) {
                    this.FieldDescriptionField = value;
                    this.RaisePropertyChanged("FieldDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FieldNameIs {
            get {
                return this.FieldNameIsField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldNameIsField, value) != true)) {
                    this.FieldNameIsField = value;
                    this.RaisePropertyChanged("FieldNameIs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FieldTypeIs {
            get {
                return this.FieldTypeIsField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldTypeIsField, value) != true)) {
                    this.FieldTypeIsField = value;
                    this.RaisePropertyChanged("FieldTypeIs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime IUDateTime {
            get {
                return this.IUDateTimeField;
            }
            set {
                if ((this.IUDateTimeField.Equals(value) != true)) {
                    this.IUDateTimeField = value;
                    this.RaisePropertyChanged("IUDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IsFieldRequired {
            get {
                return this.IsFieldRequiredField;
            }
            set {
                if ((object.ReferenceEquals(this.IsFieldRequiredField, value) != true)) {
                    this.IsFieldRequiredField = value;
                    this.RaisePropertyChanged("IsFieldRequired");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentGroup", Namespace="http://schemas.datacontract.org/2004/07/ClaimsDocsBizLogic")]
    [System.SerializableAttribute()]
    public partial class DocumentGroup : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DocumentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GroupIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime IUDateTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DocumentID {
            get {
                return this.DocumentIDField;
            }
            set {
                if ((this.DocumentIDField.Equals(value) != true)) {
                    this.DocumentIDField = value;
                    this.RaisePropertyChanged("DocumentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GroupID {
            get {
                return this.GroupIDField;
            }
            set {
                if ((this.GroupIDField.Equals(value) != true)) {
                    this.GroupIDField = value;
                    this.RaisePropertyChanged("GroupID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime IUDateTime {
            get {
                return this.IUDateTimeField;
            }
            set {
                if ((this.IUDateTimeField.Equals(value) != true)) {
                    this.IUDateTimeField = value;
                    this.RaisePropertyChanged("IUDateTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PolicyInformation", Namespace="http://schemas.datacontract.org/2004/07/ClaimsDocsBizLogic")]
    [System.SerializableAttribute()]
    public partial class PolicyInformation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaimNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PolicyCancellationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PolicyEffectiveDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PolicyLastEndorsementDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PolicyLastExpirationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PolicyNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PolicyStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PolicyTermField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProgramCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClaimNumber {
            get {
                return this.ClaimNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaimNumberField, value) != true)) {
                    this.ClaimNumberField = value;
                    this.RaisePropertyChanged("ClaimNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Department {
            get {
                return this.DepartmentField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentField, value) != true)) {
                    this.DepartmentField = value;
                    this.RaisePropertyChanged("Department");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mode {
            get {
                return this.ModeField;
            }
            set {
                if ((object.ReferenceEquals(this.ModeField, value) != true)) {
                    this.ModeField = value;
                    this.RaisePropertyChanged("Mode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PolicyCancellationDate {
            get {
                return this.PolicyCancellationDateField;
            }
            set {
                if ((this.PolicyCancellationDateField.Equals(value) != true)) {
                    this.PolicyCancellationDateField = value;
                    this.RaisePropertyChanged("PolicyCancellationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PolicyEffectiveDate {
            get {
                return this.PolicyEffectiveDateField;
            }
            set {
                if ((this.PolicyEffectiveDateField.Equals(value) != true)) {
                    this.PolicyEffectiveDateField = value;
                    this.RaisePropertyChanged("PolicyEffectiveDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PolicyLastEndorsementDate {
            get {
                return this.PolicyLastEndorsementDateField;
            }
            set {
                if ((this.PolicyLastEndorsementDateField.Equals(value) != true)) {
                    this.PolicyLastEndorsementDateField = value;
                    this.RaisePropertyChanged("PolicyLastEndorsementDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PolicyLastExpirationDate {
            get {
                return this.PolicyLastExpirationDateField;
            }
            set {
                if ((this.PolicyLastExpirationDateField.Equals(value) != true)) {
                    this.PolicyLastExpirationDateField = value;
                    this.RaisePropertyChanged("PolicyLastExpirationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PolicyNumber {
            get {
                return this.PolicyNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PolicyNumberField, value) != true)) {
                    this.PolicyNumberField = value;
                    this.RaisePropertyChanged("PolicyNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PolicyStatus {
            get {
                return this.PolicyStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.PolicyStatusField, value) != true)) {
                    this.PolicyStatusField = value;
                    this.RaisePropertyChanged("PolicyStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PolicyTerm {
            get {
                return this.PolicyTermField;
            }
            set {
                if ((object.ReferenceEquals(this.PolicyTermField, value) != true)) {
                    this.PolicyTermField = value;
                    this.RaisePropertyChanged("PolicyTerm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProgramCode {
            get {
                return this.ProgramCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProgramCodeField, value) != true)) {
                    this.ProgramCodeField = value;
                    this.RaisePropertyChanged("ProgramCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="proxClaimsDocsGenerator.IClaimsDocsGenerator")]
    public interface IClaimsDocsGenerator {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClaimsDocsGenerator/ClaimsDocsGenerateXML", ReplyAction="http://tempuri.org/IClaimsDocsGenerator/ClaimsDocsGenerateXMLResponse")]
        string ClaimsDocsGenerateXML(ClaimsDocsClient.proxClaimsDocsGenerator.Document objDocument, string strConnectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClaimsDocsGenerator/PolicyInformationGet", ReplyAction="http://tempuri.org/IClaimsDocsGenerator/PolicyInformationGetResponse")]
        ClaimsDocsClient.proxClaimsDocsGenerator.PolicyInformation PolicyInformationGet(string strPolicyNumber, string strClaimNumber, int intUKeyContact, string strConnectionString);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IClaimsDocsGeneratorChannel : ClaimsDocsClient.proxClaimsDocsGenerator.IClaimsDocsGenerator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ClaimsDocsGeneratorClient : System.ServiceModel.ClientBase<ClaimsDocsClient.proxClaimsDocsGenerator.IClaimsDocsGenerator>, ClaimsDocsClient.proxClaimsDocsGenerator.IClaimsDocsGenerator {
        
        public ClaimsDocsGeneratorClient() {
        }
        
        public ClaimsDocsGeneratorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClaimsDocsGeneratorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClaimsDocsGeneratorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClaimsDocsGeneratorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ClaimsDocsGenerateXML(ClaimsDocsClient.proxClaimsDocsGenerator.Document objDocument, string strConnectionString) {
            return base.Channel.ClaimsDocsGenerateXML(objDocument, strConnectionString);
        }
        
        public ClaimsDocsClient.proxClaimsDocsGenerator.PolicyInformation PolicyInformationGet(string strPolicyNumber, string strClaimNumber, int intUKeyContact, string strConnectionString) {
            return base.Channel.PolicyInformationGet(strPolicyNumber, strClaimNumber, intUKeyContact, strConnectionString);
        }
    }
}
