//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClaimsDocsBizLogic.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=devpolclmsql;Initial Catalog=Correspondence;User ID=website; password" +
            "=;")]
        public string DEVCorrespondenceConnectionString {
            get {
                return ((string)(this["DEVCorrespondenceConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ITQASQL02.alpha.accessgeneral.com;initial catalog=ClaimsDocs;Applicat" +
            "ion Name=ClaimsDocsBizLogic;Trusted_Connection=Yes;")]
        public string ITQACorrespondenceConnectionString {
            get {
                return ((string)(this["ITQACorrespondenceConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\devweb02\\c$\\inetpub\\wwwroot\\ClaimsDocsClient\\XMLOutputLocation\\")]
        public string DEVXMLOutputLocation {
            get {
                return ((string)(this["DEVXMLOutputLocation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=devpolclmsql;Initial Catalog=Claims;User ID=website; password=")]
        public string DEVClaimsDBConnectionString {
            get {
                return ((string)(this["DEVClaimsDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=AIHDEVSQL2K5;Initial Catalog=AMS;User ID=website;Password=")]
        public string DEVAMSDBConnectionString {
            get {
                return ((string)(this["DEVAMSDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data source=DEVPOLCLMSQL;initial catalog=ClaimsDocs;User ID=website; password=;")]
        public string DEVClaimsDocsDBConnectionString {
            get {
                return ((string)(this["DEVClaimsDocsDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\GAVWSSQ01\\c$\\inetpub\\wwwroot\\ClaimsDocsBizLogic\\XMLOutputLocation\\")]
        public string ITQAXMLOutputLocation {
            get {
                return ((string)(this["ITQAXMLOutputLocation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=AIHITQASQL2K5.alpha.accessgeneral.com;Initial Catalog=AMS;Application" +
            " Name=ClaimsDocsBizLogic;Trusted_Connection=Yes;")]
        public string ITQAAMSDBConnectionString {
            get {
                return ((string)(this["ITQAAMSDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ITQAPOLCLMSQL.alpha.AccessGeneral.com\\CLM01;initial catalog=Claims;Ap" +
            "plication Name=ClaimsDocsBizLogic;Trusted_Connection=Yes;")]
        public string ITQAClaimsDBConnectionString {
            get {
                return ((string)(this["ITQAClaimsDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ITQASQL02.alpha.accessgeneral.com;initial catalog=ClaimsDocs;Applicat" +
            "ion Name=ClaimsDocsBizLogic;Trusted_Connection=Yes;")]
        public string ITQAClaimsDocsDBConnectionString {
            get {
                return ((string)(this["ITQAClaimsDocsDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=devpolclmsql;Initial Catalog=Genesis;User ID=website; password=;")]
        public string DEVGenesisDBConnectionString {
            get {
                return ((string)(this["DEVGenesisDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ITQAPOLCLMSQL.alpha.AccessGeneral.com\\POL01;Initial Catalog=Genesis;A" +
            "pplication Name=ClaimsDocsBizLogic;Trusted_Connection=True;")]
        public string ITQAGenesisDBConnecionString {
            get {
                return ((string)(this["ITQAGenesisDBConnecionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=AIHDEVSQL2K5;Initial Catalog=AMS;User ID=website;Password=")]
        public string DEVMACHINEAMSDBConnectionString {
            get {
                return ((string)(this["DEVMACHINEAMSDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=devpolclmsql;Initial Catalog=Claims;User ID=website; password=")]
        public string DEVMACHINEClaimsDBConnectionString {
            get {
                return ((string)(this["DEVMACHINEClaimsDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data source=DEVPOLCLMSQL;Integrated Security=True;initial catalog=ClaimsDocs")]
        public string DEVMACHINEClaimsDocsDBConnectionString {
            get {
                return ((string)(this["DEVMACHINEClaimsDocsDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=devpolclmsql.development.accessgeneral.com;Initial Catalog=Correspond" +
            "ence;User ID=website; password=;Trusted_Connection=True;")]
        public string DEVMACHINECorrespondenceConnectionString {
            get {
                return ((string)(this["DEVMACHINECorrespondenceConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=devpolclmsql.development.accessgeneral.com;Initial Catalog=Genesis;Us" +
            "er ID=website; password=;Trusted_Connection=True;")]
        public string DEVMACHINEGenesisDBConnectionString {
            get {
                return ((string)(this["DEVMACHINEGenesisDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\dev016dnet.accessgeneral.com\\c$\\Documents and Settings\\kphifer\\My Documents\\Loc" +
            "alData\\ProjectInfo\\Claims\\DataSamples\\ClaimsDocsOuput\\")]
        public string DEVMACHINEXMLOutputLocation {
            get {
                return ((string)(this["DEVMACHINEXMLOutputLocation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://devweb02/ClaimsDocsClient/XMLOutputLocation/")]
        public string DEVXMLUNCOutputLocation {
            get {
                return ((string)(this["DEVXMLUNCOutputLocation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\dev016dnet.accessgeneral.com\\c$\\Documents and Settings\\kphifer\\My Documents\\Loc" +
            "alData\\ProjectInfo\\Claims\\DataSamples\\ClaimsDocsOuput\\")]
        public string DEVMACHINEXMLUNCOutputLocation {
            get {
                return ((string)(this["DEVMACHINEXMLUNCOutputLocation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://GAVWSSQ01/ClaimsDocsBizLogic/XMLOutputLocation/")]
        public string ITQAXMLUNCOutputLocation {
            get {
                return ((string)(this["ITQAXMLUNCOutputLocation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FormatName:DIRECT=OS:AIHDevAutoSrv01\\private$\\claimsdocs_replyq")]
        public string DEVDocumakerReplyQueue {
            get {
                return ((string)(this["DEVDocumakerReplyQueue"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FormatName:DIRECT=OS:AIHDevAutoSrv01\\private$\\claimsdocs_requestq")]
        public string DEVDocumakerRequestQueue {
            get {
                return ((string)(this["DEVDocumakerRequestQueue"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AIH_LETTERS_DEV")]
        public string DEVDocumakerEnvironment {
            get {
                return ((string)(this["DEVDocumakerEnvironment"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\AIHDEVIDOCUMAKER")]
        public string DEVDocumakerUNCRoot {
            get {
                return ((string)(this["DEVDocumakerUNCRoot"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:30")]
        public global::System.TimeSpan DocuMakerReceiveTimeout {
            get {
                return ((global::System.TimeSpan)(this["DocuMakerReceiveTimeout"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int DocuMakerPeekPauseInSeconds {
            get {
                return ((int)(this["DocuMakerPeekPauseInSeconds"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DocuMaker")]
        public string DocumentGenerator {
            get {
                return ((string)(this["DocumentGenerator"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TBD")]
        public string ClaimsDocsNameSpace {
            get {
                return ((string)(this["ClaimsDocsNameSpace"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CLMS")]
        public string ImageRightClaimsDrawer {
            get {
                return ((string)(this["ImageRightClaimsDrawer"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ClaimsDocs Generated Document")]
        public string ImageRightReason {
            get {
                return ((string)(this["ImageRightReason"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("27")]
        public int ImageRightFlowID {
            get {
                return ((int)(this["ImageRightFlowID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int ImageRightStepID {
            get {
                return ((int)(this["ImageRightStepID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ClaimsDocs Generated Document")]
        public string ImageRightDescription {
            get {
                return ((string)(this["ImageRightDescription"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int ImageRightPriority {
            get {
                return ((int)(this["ImageRightPriority"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://aihirwsdev01.development/irwebservice/irwebservice.asmx")]
        public string DEVMACHINEImageRightWSURL {
            get {
                return ((string)(this["DEVMACHINEImageRightWSURL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ADMIN")]
        public string DEVMACHINEImageRightLogin {
            get {
                return ((string)(this["DEVMACHINEImageRightLogin"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IRADMIN")]
        public string DEVMACHINEImageRightPassword {
            get {
                return ((string)(this["DEVMACHINEImageRightPassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://aihirwsdev01.development.accessgeneral.com/irwebservice/irwebservice.asmx")]
        public string DEVImageRightWSURL {
            get {
                return ((string)(this["DEVImageRightWSURL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ADMIN")]
        public string DEVImageRightLogin {
            get {
                return ((string)(this["DEVImageRightLogin"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IRADMIN")]
        public string DEVImageRightPassword {
            get {
                return ((string)(this["DEVImageRightPassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AIH_LETTERS_ITQA")]
        public string ITQADocumakerEnvironment {
            get {
                return ((string)(this["ITQADocumakerEnvironment"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FormatName:DIRECT=OS:AIHITQAAutoSrv\\PRIVATE$\\ids_replyq")]
        public string ITQADocumakerReplyQueue {
            get {
                return ((string)(this["ITQADocumakerReplyQueue"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FormatName:DIRECT=OS:AIHITQAAutoSrv\\PRIVATE$\\ids_requestq")]
        public string ITQADocumakerRequestQueue {
            get {
                return ((string)(this["ITQADocumakerRequestQueue"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\AIHITQADocuPresentment.alpha.accessgeneral.com")]
        public string ITQADocumakerUNCRoot {
            get {
                return ((string)(this["ITQADocumakerUNCRoot"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ADMIN")]
        public string ITQAImageRightLogin {
            get {
                return ((string)(this["ITQAImageRightLogin"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IRADMIN")]
        public string ITQAImageRightPassword {
            get {
                return ((string)(this["ITQAImageRightPassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://aihitqawsir01.alpha.accessgeneral.com/irwebservice/irwebservice.asmx")]
        public string ITQAImageRightWSURL {
            get {
                return ((string)(this["ITQAImageRightWSURL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\dev016dnet.accessgeneral.com\\c$\\Documents and Settings\\kphifer\\My Documents\\Loc" +
            "alData\\Projects\\ClaimsDocsSolution\\ClaimsDocsBizLogic\\ClaimsDocsBizLogicLog\\Clai" +
            "msDocsBizLogicLogFile.txt")]
        public string DEVMACHINEClaimsDocsBizLogicLogFile {
            get {
                return ((string)(this["DEVMACHINEClaimsDocsBizLogicLogFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\devweb02\\c$\\inetpub\\wwwroot\\ClaimsDocsBizLogic\\ClaimsDocsBizLogicLog\\ClaimsDocs" +
            "BizLogicLogFile.txt")]
        public string DEVClaimsDocsBizLogicLogFile {
            get {
                return ((string)(this["DEVClaimsDocsBizLogicLogFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\GAVWSSQ01\\c$\\inetpub\\wwwroot\\ClaimsDocsBizLogic\\ClaimsDocsBizLogicLog\\ClaimsDoc" +
            "sBizLogicLogFile.txt")]
        public string ITQAClaimsDocsBizLogicLogFile {
            get {
                return ((string)(this["ITQAClaimsDocsBizLogicLogFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AIHEXCH01.accessgeneral.com")]
        public string DEVMACHINESmtpHost {
            get {
                return ((string)(this["DEVMACHINESmtpHost"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AIHEXCH01.accessgeneral.com")]
        public string DEVSmtpHost {
            get {
                return ((string)(this["DEVSmtpHost"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AIHEXCH01.accessgeneral.com")]
        public string ITQASmtpHost {
            get {
                return ((string)(this["ITQASmtpHost"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ClaimsDocs : Document Declined Details")]
        public string EMailDeclineSubject {
            get {
                return ((string)(this["EMailDeclineSubject"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=PRODSQL11\\IA;Initial Catalog=AMS;Application Name=ClaimsDocsBizLogic;" +
            "Trusted_Connection=Yes;Connection Timeout=120;Connection Lifetime=0;Min Pool Siz" +
            "e=0;Max Pool Size=500;Pooling=true;")]
        public string PRODAMSDBConnectionString {
            get {
                return ((string)(this["PRODAMSDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=PRODSQL06\\CLAIMS;initial catalog=Claims;Application Name=ClaimsDocsBi" +
            "zLogic;Trusted_Connection=Yes;Connection Timeout=120;Connection Lifetime=0;Min P" +
            "ool Size=0;Max Pool Size=500;Pooling=true;")]
        public string PRODClaimsDBConnectionString {
            get {
                return ((string)(this["PRODClaimsDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\prodfil01\\ClaimsDocsXMLOutputLocation\\ClaimsDocsBizLogicLogFile.txt")]
        public string PRODClaimsDocsBizLogicLogFile {
            get {
                return ((string)(this["PRODClaimsDocsBizLogicLogFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=PRODSQL05\\POLICY;Initial Catalog=Genesis;Application Name=ClaimsDocsB" +
            "izLogic;Trusted_Connection=True;")]
        public string PRODGenesisDBConnecionString {
            get {
                return ((string)(this["PRODGenesisDBConnecionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AIH_LETTERS_PROD")]
        public string PRODDocumakerEnvironment {
            get {
                return ((string)(this["PRODDocumakerEnvironment"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FormatName:DIRECT=OS:PRODWSS05\\private$\\ids_replyq")]
        public string PRODDocumakerReplyQueue {
            get {
                return ((string)(this["PRODDocumakerReplyQueue"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FormatName:DIRECT=OS:PRODWSS05\\private$\\ids_requestq")]
        public string PRODDocumakerRequestQueue {
            get {
                return ((string)(this["PRODDocumakerRequestQueue"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\PRODAPP10")]
        public string PRODDocumakerUNCRoot {
            get {
                return ((string)(this["PRODDocumakerUNCRoot"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IRWEB")]
        public string PRODImageRightLogin {
            get {
                return ((string)(this["PRODImageRightLogin"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ACC3SS")]
        public string PRODImageRightPassword {
            get {
                return ((string)(this["PRODImageRightPassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://prodwss04/irwebservice/irwebservice.asmx")]
        public string PRODImageRightWSURL {
            get {
                return ((string)(this["PRODImageRightWSURL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AIHEXCH01.accessgeneral.com")]
        public string PRODSmtpHost {
            get {
                return ((string)(this["PRODSmtpHost"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\prodfil01\\ClaimsDocsXMLOutputLocation\\")]
        public string PRODXMLOutputLocation {
            get {
                return ((string)(this["PRODXMLOutputLocation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file://prodfil01/ClaimsDocsXMLOutputLocation/")]
        public string PRODXMLUNCOutputLocation {
            get {
                return ((string)(this["PRODXMLUNCOutputLocation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=TESTSQL04;Initial Catalog=AMS;Application Name=ClaimsDocsBizLogic;Tru" +
            "sted_Connection=Yes;")]
        public string UATAMSDBConnectionString {
            get {
                return ((string)(this["UATAMSDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\testfil01\\ClaimsDocsXMLOutputLocation\\ClaimsDocsBizLogicLogFile.txt")]
        public string UATClaimsDocsBizLogicLogFile {
            get {
                return ((string)(this["UATClaimsDocsBizLogicLogFile"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=TESTSQL08;initial catalog=ClaimsDocs;Application Name=ClaimsDocsBizLo" +
            "gic;Trusted_Connection=Yes;")]
        public string UATClaimsDocsDBConnectionString {
            get {
                return ((string)(this["UATClaimsDocsDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=POLICY_UAT;Initial Catalog=Genesis;Application Name=ClaimsDocsBizLogi" +
            "c;Trusted_Connection=True;")]
        public string UATGenesisDBConnecionString {
            get {
                return ((string)(this["UATGenesisDBConnecionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=TESTSQL08;initial catalog=ClaimsDocs;Application Name=ClaimsDocsBizLo" +
            "gic;Trusted_Connection=Yes;")]
        public string UATCorrespondenceConnectionString {
            get {
                return ((string)(this["UATCorrespondenceConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AIH_LETTERS_UAT")]
        public string UATDocumakerEnvironment {
            get {
                return ((string)(this["UATDocumakerEnvironment"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FormatName:DIRECT=OS:TESTWSS05\\private$\\ids_replyq")]
        public string UATDocumakerReplyQueue {
            get {
                return ((string)(this["UATDocumakerReplyQueue"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FormatName:DIRECT=OS:TESTWSS05\\private$\\ids_requestq")]
        public string UATDocumakerRequestQueue {
            get {
                return ((string)(this["UATDocumakerRequestQueue"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\TESTAPP10")]
        public string UATDocumakerUNCRoot {
            get {
                return ((string)(this["UATDocumakerUNCRoot"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IRWEB")]
        public string UATImageRightLogin {
            get {
                return ((string)(this["UATImageRightLogin"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ACC3SS")]
        public string UATImageRightPassword {
            get {
                return ((string)(this["UATImageRightPassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://testwss04a/irwebservice/irwebservice.asmx")]
        public string UATImageRightWSURL {
            get {
                return ((string)(this["UATImageRightWSURL"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AIHEXCH01.accessgeneral.com")]
        public string UATSmtpHost {
            get {
                return ((string)(this["UATSmtpHost"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\testfil01\\ClaimsDocsXMLOutputLocation\\")]
        public string UATXMLOutputLocation {
            get {
                return ((string)(this["UATXMLOutputLocation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("file://testfil01/ClaimsDocsXMLOutputLocation/")]
        public string UATXMLUNCOutputLocation {
            get {
                return ((string)(this["UATXMLUNCOutputLocation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=PRODSQL15\\MD;initial catalog=ClaimsDocs;Application Name=ClaimsDocsBi" +
            "zLogic;Trusted_Connection=Yes;Connection Timeout=120;Connection Lifetime=0;Min P" +
            "ool Size=0;Max Pool Size=500;Pooling=true;")]
        public string PRODClaimsDocsDBConnectionString {
            get {
                return ((string)(this["PRODClaimsDocsDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=PRODSQL15\\MD;initial catalog=ClaimsDocs;Application Name=ClaimsDocsBi" +
            "zLogic;Trusted_Connection=Yes;Connection Timeout=120;Connection Lifetime=0;Min P" +
            "ool Size=0;Max Pool Size=500;Pooling=true;")]
        public string PRODCorrespondenceConnectionString {
            get {
                return ((string)(this["PRODCorrespondenceConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int DocuMakerNumberOfTries {
            get {
                return ((int)(this["DocuMakerNumberOfTries"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int NumberOfResponseTries {
            get {
                return ((int)(this["NumberOfResponseTries"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int MessageQueueLoopTries {
            get {
                return ((int)(this["MessageQueueLoopTries"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=TESTSQL22;initial catalog=Claims;Application Name=ClaimsDocsBizLogic;" +
            "Trusted_Connection=Yes;")]
        public string UATClaimsDBConnectionString {
            get {
                return ((string)(this["UATClaimsDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ITQA")]
        public string RunMode {
            get {
                return ((string)(this["RunMode"]));
            }
        }
    }
}
