//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClaimsDocsClient.proxyCDSupport {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClaimsDocsLog", Namespace="http://schemas.datacontract.org/2004/07/ClaimsDocsBizLogic")]
    [System.SerializableAttribute()]
    public partial class ClaimsDocsLog : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ClaimsDocsLogIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionIsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime IUDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LogSourceTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LogTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogTypeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageIsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StackTraceIsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ClaimsDocsLogID {
            get {
                return this.ClaimsDocsLogIDField;
            }
            set {
                if ((this.ClaimsDocsLogIDField.Equals(value) != true)) {
                    this.ClaimsDocsLogIDField = value;
                    this.RaisePropertyChanged("ClaimsDocsLogID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExceptionIs {
            get {
                return this.ExceptionIsField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionIsField, value) != true)) {
                    this.ExceptionIsField = value;
                    this.RaisePropertyChanged("ExceptionIs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime IUDateTime {
            get {
                return this.IUDateTimeField;
            }
            set {
                if ((this.IUDateTimeField.Equals(value) != true)) {
                    this.IUDateTimeField = value;
                    this.RaisePropertyChanged("IUDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LogSourceTypeID {
            get {
                return this.LogSourceTypeIDField;
            }
            set {
                if ((this.LogSourceTypeIDField.Equals(value) != true)) {
                    this.LogSourceTypeIDField = value;
                    this.RaisePropertyChanged("LogSourceTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LogTypeID {
            get {
                return this.LogTypeIDField;
            }
            set {
                if ((this.LogTypeIDField.Equals(value) != true)) {
                    this.LogTypeIDField = value;
                    this.RaisePropertyChanged("LogTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogTypeName {
            get {
                return this.LogTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LogTypeNameField, value) != true)) {
                    this.LogTypeNameField = value;
                    this.RaisePropertyChanged("LogTypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageIs {
            get {
                return this.MessageIsField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageIsField, value) != true)) {
                    this.MessageIsField = value;
                    this.RaisePropertyChanged("MessageIs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SourceName {
            get {
                return this.SourceNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceNameField, value) != true)) {
                    this.SourceNameField = value;
                    this.RaisePropertyChanged("SourceName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTraceIs {
            get {
                return this.StackTraceIsField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceIsField, value) != true)) {
                    this.StackTraceIsField = value;
                    this.RaisePropertyChanged("StackTraceIs");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidateResult", Namespace="http://schemas.datacontract.org/2004/07/ClaimsDocsBizLogic")]
    [System.SerializableAttribute()]
    public partial class ValidateResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ValidCheckField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValidationFocusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValidationResultMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ValidCheck {
            get {
                return this.ValidCheckField;
            }
            set {
                if ((this.ValidCheckField.Equals(value) != true)) {
                    this.ValidCheckField = value;
                    this.RaisePropertyChanged("ValidCheck");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValidationFocus {
            get {
                return this.ValidationFocusField;
            }
            set {
                if ((object.ReferenceEquals(this.ValidationFocusField, value) != true)) {
                    this.ValidationFocusField = value;
                    this.RaisePropertyChanged("ValidationFocus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValidationResultMessage {
            get {
                return this.ValidationResultMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ValidationResultMessageField, value) != true)) {
                    this.ValidationResultMessageField = value;
                    this.RaisePropertyChanged("ValidationResultMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EMailSendRequest", Namespace="http://schemas.datacontract.org/2004/07/ClaimsDocsBizLogic")]
    [System.SerializableAttribute()]
    public partial class EMailSendRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromEMailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToEMailAddressField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Body {
            get {
                return this.BodyField;
            }
            set {
                if ((object.ReferenceEquals(this.BodyField, value) != true)) {
                    this.BodyField = value;
                    this.RaisePropertyChanged("Body");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromEMailAddress {
            get {
                return this.FromEMailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.FromEMailAddressField, value) != true)) {
                    this.FromEMailAddressField = value;
                    this.RaisePropertyChanged("FromEMailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject {
            get {
                return this.SubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectField, value) != true)) {
                    this.SubjectField = value;
                    this.RaisePropertyChanged("Subject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToEMailAddress {
            get {
                return this.ToEMailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.ToEMailAddressField, value) != true)) {
                    this.ToEMailAddressField = value;
                    this.RaisePropertyChanged("ToEMailAddress");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="proxyCDSupport.ICDSupport")]
    public interface ICDSupport {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDSupport/ClaimsDocsLogCreate", ReplyAction="http://tempuri.org/ICDSupport/ClaimsDocsLogCreateResponse")]
        int ClaimsDocsLogCreate(ClaimsDocsClient.proxyCDSupport.ClaimsDocsLog objClaimsDocsLog, string strConnectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDSupport/ClaimsDocsLogSearch", ReplyAction="http://tempuri.org/ICDSupport/ClaimsDocsLogSearchResponse")]
        System.Collections.Generic.List<ClaimsDocsClient.proxyCDSupport.ClaimsDocsLog> ClaimsDocsLogSearch(string strSQLString, string strConnectionString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDSupport/ValidateWCFServiceCall", ReplyAction="http://tempuri.org/ICDSupport/ValidateWCFServiceCallResponse")]
        ClaimsDocsClient.proxyCDSupport.ValidateResult ValidateWCFServiceCall();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDSupport/ValidateXMLOutputLocation", ReplyAction="http://tempuri.org/ICDSupport/ValidateXMLOutputLocationResponse")]
        ClaimsDocsClient.proxyCDSupport.ValidateResult ValidateXMLOutputLocation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDSupport/ValidateMessageQueue", ReplyAction="http://tempuri.org/ICDSupport/ValidateMessageQueueResponse")]
        ClaimsDocsClient.proxyCDSupport.ValidateResult ValidateMessageQueue();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDSupport/ValidateClaimsDBConnection", ReplyAction="http://tempuri.org/ICDSupport/ValidateClaimsDBConnectionResponse")]
        ClaimsDocsClient.proxyCDSupport.ValidateResult ValidateClaimsDBConnection();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDSupport/ValidateClaimsDocsDBConnection", ReplyAction="http://tempuri.org/ICDSupport/ValidateClaimsDocsDBConnectionResponse")]
        ClaimsDocsClient.proxyCDSupport.ValidateResult ValidateClaimsDocsDBConnection();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDSupport/ValidateCorrespondenceDBConnection", ReplyAction="http://tempuri.org/ICDSupport/ValidateCorrespondenceDBConnectionResponse")]
        ClaimsDocsClient.proxyCDSupport.ValidateResult ValidateCorrespondenceDBConnection();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDSupport/ValidateAMSDBConnection", ReplyAction="http://tempuri.org/ICDSupport/ValidateAMSDBConnectionResponse")]
        ClaimsDocsClient.proxyCDSupport.ValidateResult ValidateAMSDBConnection();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDSupport/ValidateGenesisDBConnection", ReplyAction="http://tempuri.org/ICDSupport/ValidateGenesisDBConnectionResponse")]
        ClaimsDocsClient.proxyCDSupport.ValidateResult ValidateGenesisDBConnection();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDSupport/ValidateAMSPointToClaimsLinkedServer", ReplyAction="http://tempuri.org/ICDSupport/ValidateAMSPointToClaimsLinkedServerResponse")]
        ClaimsDocsClient.proxyCDSupport.ValidateResult ValidateAMSPointToClaimsLinkedServer(int intClaimUKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDSupport/ValidateAMSPointToGenesisLinkedServer", ReplyAction="http://tempuri.org/ICDSupport/ValidateAMSPointToGenesisLinkedServerResponse")]
        ClaimsDocsClient.proxyCDSupport.ValidateResult ValidateAMSPointToGenesisLinkedServer(string strPolicyNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDSupport/ValidateClaimsPointToGenesisLinkedServer", ReplyAction="http://tempuri.org/ICDSupport/ValidateClaimsPointToGenesisLinkedServerResponse")]
        ClaimsDocsClient.proxyCDSupport.ValidateResult ValidateClaimsPointToGenesisLinkedServer(int intContactUKey, int intVehicleFound);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDSupport/ValidateAddressRegEx", ReplyAction="http://tempuri.org/ICDSupport/ValidateAddressRegExResponse")]
        bool ValidateAddressRegEx(string strAddresseeName, string strAddressLine1, string strCity, string strState, string strZipCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDSupport/SendEMailMessage", ReplyAction="http://tempuri.org/ICDSupport/SendEMailMessageResponse")]
        bool SendEMailMessage(ClaimsDocsClient.proxyCDSupport.EMailSendRequest objEMailSendRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICDSupportChannel : ClaimsDocsClient.proxyCDSupport.ICDSupport, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CDSupportClient : System.ServiceModel.ClientBase<ClaimsDocsClient.proxyCDSupport.ICDSupport>, ClaimsDocsClient.proxyCDSupport.ICDSupport {
        
        public CDSupportClient() {
        }
        
        public CDSupportClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CDSupportClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CDSupportClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CDSupportClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int ClaimsDocsLogCreate(ClaimsDocsClient.proxyCDSupport.ClaimsDocsLog objClaimsDocsLog, string strConnectionString) {
            return base.Channel.ClaimsDocsLogCreate(objClaimsDocsLog, strConnectionString);
        }
        
        public System.Collections.Generic.List<ClaimsDocsClient.proxyCDSupport.ClaimsDocsLog> ClaimsDocsLogSearch(string strSQLString, string strConnectionString) {
            return base.Channel.ClaimsDocsLogSearch(strSQLString, strConnectionString);
        }
        
        public ClaimsDocsClient.proxyCDSupport.ValidateResult ValidateWCFServiceCall() {
            return base.Channel.ValidateWCFServiceCall();
        }
        
        public ClaimsDocsClient.proxyCDSupport.ValidateResult ValidateXMLOutputLocation() {
            return base.Channel.ValidateXMLOutputLocation();
        }
        
        public ClaimsDocsClient.proxyCDSupport.ValidateResult ValidateMessageQueue() {
            return base.Channel.ValidateMessageQueue();
        }
        
        public ClaimsDocsClient.proxyCDSupport.ValidateResult ValidateClaimsDBConnection() {
            return base.Channel.ValidateClaimsDBConnection();
        }
        
        public ClaimsDocsClient.proxyCDSupport.ValidateResult ValidateClaimsDocsDBConnection() {
            return base.Channel.ValidateClaimsDocsDBConnection();
        }
        
        public ClaimsDocsClient.proxyCDSupport.ValidateResult ValidateCorrespondenceDBConnection() {
            return base.Channel.ValidateCorrespondenceDBConnection();
        }
        
        public ClaimsDocsClient.proxyCDSupport.ValidateResult ValidateAMSDBConnection() {
            return base.Channel.ValidateAMSDBConnection();
        }
        
        public ClaimsDocsClient.proxyCDSupport.ValidateResult ValidateGenesisDBConnection() {
            return base.Channel.ValidateGenesisDBConnection();
        }
        
        public ClaimsDocsClient.proxyCDSupport.ValidateResult ValidateAMSPointToClaimsLinkedServer(int intClaimUKey) {
            return base.Channel.ValidateAMSPointToClaimsLinkedServer(intClaimUKey);
        }
        
        public ClaimsDocsClient.proxyCDSupport.ValidateResult ValidateAMSPointToGenesisLinkedServer(string strPolicyNumber) {
            return base.Channel.ValidateAMSPointToGenesisLinkedServer(strPolicyNumber);
        }
        
        public ClaimsDocsClient.proxyCDSupport.ValidateResult ValidateClaimsPointToGenesisLinkedServer(int intContactUKey, int intVehicleFound) {
            return base.Channel.ValidateClaimsPointToGenesisLinkedServer(intContactUKey, intVehicleFound);
        }
        
        public bool ValidateAddressRegEx(string strAddresseeName, string strAddressLine1, string strCity, string strState, string strZipCode) {
            return base.Channel.ValidateAddressRegEx(strAddresseeName, strAddressLine1, strCity, strState, strZipCode);
        }
        
        public bool SendEMailMessage(ClaimsDocsClient.proxyCDSupport.EMailSendRequest objEMailSendRequest) {
            return base.Channel.SendEMailMessage(objEMailSendRequest);
        }
    }
}
