//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClaimsDocsBizLogic.DocumentStorageWS1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.accessgeneral.com/DocumentStorage/", ConfigurationName="DocumentStorageWS1.DocumentStorageWSSoap")]
    public interface DocumentStorageWSSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.accessgeneral.com/DocumentStorage/SaveDocument", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClaimsDocsBizLogic.DocumentStorageWS1.SaveDocumentResponse SaveDocument(ClaimsDocsBizLogic.DocumentStorageWS1.SaveDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.accessgeneral.com/DocumentStorage/SaveDocumentTrx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClaimsDocsBizLogic.DocumentStorageWS1.SaveDocumentTrxResponse SaveDocumentTrx(ClaimsDocsBizLogic.DocumentStorageWS1.SaveDocumentTrxRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.accessgeneral.com/DocumentStorage/SaveExceptions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClaimsDocsBizLogic.DocumentStorageWS1.SaveExceptionsResponse SaveExceptions(ClaimsDocsBizLogic.DocumentStorageWS1.SaveExceptionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.accessgeneral.com/DocumentStorage/SaveExceptionsTrx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClaimsDocsBizLogic.DocumentStorageWS1.SaveExceptionsTrxResponse SaveExceptionsTrx(ClaimsDocsBizLogic.DocumentStorageWS1.SaveExceptionsTrxRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.accessgeneral.com/DocumentStorage/GetDocument", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClaimsDocsBizLogic.DocumentStorageWS1.GetDocumentResponse GetDocument(ClaimsDocsBizLogic.DocumentStorageWS1.GetDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.accessgeneral.com/DocumentStorage/GetDocumentTrx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClaimsDocsBizLogic.DocumentStorageWS1.GetDocumentTrxResponse GetDocumentTrx(ClaimsDocsBizLogic.DocumentStorageWS1.GetDocumentTrxRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.accessgeneral.com/DocumentStorage/CreateTask", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClaimsDocsBizLogic.DocumentStorageWS1.CreateTaskResponse CreateTask(ClaimsDocsBizLogic.DocumentStorageWS1.CreateTaskRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.accessgeneral.com/DocumentStorage/CreateTaskTrx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClaimsDocsBizLogic.DocumentStorageWS1.CreateTaskTrxResponse CreateTaskTrx(ClaimsDocsBizLogic.DocumentStorageWS1.CreateTaskTrxRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.accessgeneral.com/DocumentStorage/FindDocument", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ClaimsDocsBizLogic.DocumentStorageWS1.FindDocumentResponse FindDocument(ClaimsDocsBizLogic.DocumentStorageWS1.FindDocumentRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.accessgeneral.com/schemas/DocumentGeneration/DocumentInfoV1.0")]
    public partial class DocumentInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string docKeyField;
        
        private string docPathField;
        
        private string docURLField;
        
        private string docTypeField;
        
        private string docDateField;
        
        private string transTypeField;
        
        private string drawerField;
        
        private string fileNumberField;
        
        private ArrayOfDocumentInfoVarVar[] varsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string DocKey {
            get {
                return this.docKeyField;
            }
            set {
                this.docKeyField = value;
                this.RaisePropertyChanged("DocKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string DocPath {
            get {
                return this.docPathField;
            }
            set {
                this.docPathField = value;
                this.RaisePropertyChanged("DocPath");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string DocURL {
            get {
                return this.docURLField;
            }
            set {
                this.docURLField = value;
                this.RaisePropertyChanged("DocURL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string DocType {
            get {
                return this.docTypeField;
            }
            set {
                this.docTypeField = value;
                this.RaisePropertyChanged("DocType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string DocDate {
            get {
                return this.docDateField;
            }
            set {
                this.docDateField = value;
                this.RaisePropertyChanged("DocDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string TransType {
            get {
                return this.transTypeField;
            }
            set {
                this.transTypeField = value;
                this.RaisePropertyChanged("TransType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string Drawer {
            get {
                return this.drawerField;
            }
            set {
                this.drawerField = value;
                this.RaisePropertyChanged("Drawer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string FileNumber {
            get {
                return this.fileNumberField;
            }
            set {
                this.fileNumberField = value;
                this.RaisePropertyChanged("FileNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Var", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ArrayOfDocumentInfoVarVar[] Vars {
            get {
                return this.varsField;
            }
            set {
                this.varsField = value;
                this.RaisePropertyChanged("Vars");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.accessgeneral.com/schemas/DocumentGeneration/DocumentInfoV1.0")]
    public partial class ArrayOfDocumentInfoVarVar : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34209")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.accessgeneral.com/schemas/DocumentGeneration/DocumentInfoV1.0")]
    public partial class DocumentInfoVar : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveDocument", WrapperNamespace="http://www.accessgeneral.com/DocumentStorage/", IsWrapped=true)]
    public partial class SaveDocumentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.accessgeneral.com/DocumentStorage/", Order=0)]
        public ClaimsDocsBizLogic.DocumentStorageWS1.DocumentInfo DocumentInfo;
        
        public SaveDocumentRequest() {
        }
        
        public SaveDocumentRequest(ClaimsDocsBizLogic.DocumentStorageWS1.DocumentInfo DocumentInfo) {
            this.DocumentInfo = DocumentInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveDocumentResponse", WrapperNamespace="http://www.accessgeneral.com/DocumentStorage/", IsWrapped=true)]
    public partial class SaveDocumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.accessgeneral.com/DocumentStorage/", Order=0)]
        public ClaimsDocsBizLogic.DocumentStorageWS1.DocumentInfo DocumentInfo;
        
        public SaveDocumentResponse() {
        }
        
        public SaveDocumentResponse(ClaimsDocsBizLogic.DocumentStorageWS1.DocumentInfo DocumentInfo) {
            this.DocumentInfo = DocumentInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveDocumentTrx", WrapperNamespace="http://www.accessgeneral.com/DocumentStorage/", IsWrapped=true)]
    public partial class SaveDocumentTrxRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.accessgeneral.com/DocumentStorage/", Order=0)]
        public System.Guid transactionID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.accessgeneral.com/DocumentStorage/", Order=1)]
        public ClaimsDocsBizLogic.DocumentStorageWS1.DocumentInfo DocumentInfo;
        
        public SaveDocumentTrxRequest() {
        }
        
        public SaveDocumentTrxRequest(System.Guid transactionID, ClaimsDocsBizLogic.DocumentStorageWS1.DocumentInfo DocumentInfo) {
            this.transactionID = transactionID;
            this.DocumentInfo = DocumentInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveDocumentTrxResponse", WrapperNamespace="http://www.accessgeneral.com/DocumentStorage/", IsWrapped=true)]
    public partial class SaveDocumentTrxResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.accessgeneral.com/DocumentStorage/", Order=0)]
        public ClaimsDocsBizLogic.DocumentStorageWS1.DocumentInfo DocumentInfo;
        
        public SaveDocumentTrxResponse() {
        }
        
        public SaveDocumentTrxResponse(ClaimsDocsBizLogic.DocumentStorageWS1.DocumentInfo DocumentInfo) {
            this.DocumentInfo = DocumentInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveExceptions", WrapperNamespace="http://www.accessgeneral.com/DocumentStorage/", IsWrapped=true)]
    public partial class SaveExceptionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.accessgeneral.com/DocumentStorage/", Order=0)]
        public ClaimsDocsBizLogic.DocumentStorageWS1.DocumentInfo DocumentInfo;
        
        public SaveExceptionsRequest() {
        }
        
        public SaveExceptionsRequest(ClaimsDocsBizLogic.DocumentStorageWS1.DocumentInfo DocumentInfo) {
            this.DocumentInfo = DocumentInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveExceptionsResponse", WrapperNamespace="http://www.accessgeneral.com/DocumentStorage/", IsWrapped=true)]
    public partial class SaveExceptionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.accessgeneral.com/DocumentStorage/", Order=0)]
        public ClaimsDocsBizLogic.DocumentStorageWS1.DocumentInfo DocumentInfo;
        
        public SaveExceptionsResponse() {
        }
        
        public SaveExceptionsResponse(ClaimsDocsBizLogic.DocumentStorageWS1.DocumentInfo DocumentInfo) {
            this.DocumentInfo = DocumentInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveExceptionsTrx", WrapperNamespace="http://www.accessgeneral.com/DocumentStorage/", IsWrapped=true)]
    public partial class SaveExceptionsTrxRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.accessgeneral.com/DocumentStorage/", Order=0)]
        public System.Guid transactionID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.accessgeneral.com/DocumentStorage/", Order=1)]
        public ClaimsDocsBizLogic.DocumentStorageWS1.DocumentInfo DocumentInfo;
        
        public SaveExceptionsTrxRequest() {
        }
        
        public SaveExceptionsTrxRequest(System.Guid transactionID, ClaimsDocsBizLogic.DocumentStorageWS1.DocumentInfo DocumentInfo) {
            this.transactionID = transactionID;
            this.DocumentInfo = DocumentInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveExceptionsTrxResponse", WrapperNamespace="http://www.accessgeneral.com/DocumentStorage/", IsWrapped=true)]
    public partial class SaveExceptionsTrxResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.accessgeneral.com/DocumentStorage/", Order=0)]
        public ClaimsDocsBizLogic.DocumentStorageWS1.DocumentInfo DocumentInfo;
        
        public SaveExceptionsTrxResponse() {
        }
        
        public SaveExceptionsTrxResponse(ClaimsDocsBizLogic.DocumentStorageWS1.DocumentInfo DocumentInfo) {
            this.DocumentInfo = DocumentInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDocument", WrapperNamespace="http://www.accessgeneral.com/DocumentStorage/", IsWrapped=true)]
    public partial class GetDocumentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.accessgeneral.com/DocumentStorage/", Order=0)]
        public ClaimsDocsBizLogic.DocumentStorageWS1.DocumentInfo DocumentInfo;
        
        public GetDocumentRequest() {
        }
        
        public GetDocumentRequest(ClaimsDocsBizLogic.DocumentStorageWS1.DocumentInfo DocumentInfo) {
            this.DocumentInfo = DocumentInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDocumentResponse", WrapperNamespace="http://www.accessgeneral.com/DocumentStorage/", IsWrapped=true)]
    public partial class GetDocumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.accessgeneral.com/DocumentStorage/", Order=0)]
        public ClaimsDocsBizLogic.DocumentStorageWS1.DocumentInfo DocumentInfo;
        
        public GetDocumentResponse() {
        }
        
        public GetDocumentResponse(ClaimsDocsBizLogic.DocumentStorageWS1.DocumentInfo DocumentInfo) {
            this.DocumentInfo = DocumentInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDocumentTrx", WrapperNamespace="http://www.accessgeneral.com/DocumentStorage/", IsWrapped=true)]
    public partial class GetDocumentTrxRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.accessgeneral.com/DocumentStorage/", Order=0)]
        public System.Guid transactionID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.accessgeneral.com/DocumentStorage/", Order=1)]
        public ClaimsDocsBizLogic.DocumentStorageWS1.DocumentInfo DocumentInfo;
        
        public GetDocumentTrxRequest() {
        }
        
        public GetDocumentTrxRequest(System.Guid transactionID, ClaimsDocsBizLogic.DocumentStorageWS1.DocumentInfo DocumentInfo) {
            this.transactionID = transactionID;
            this.DocumentInfo = DocumentInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDocumentTrxResponse", WrapperNamespace="http://www.accessgeneral.com/DocumentStorage/", IsWrapped=true)]
    public partial class GetDocumentTrxResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.accessgeneral.com/DocumentStorage/", Order=0)]
        public ClaimsDocsBizLogic.DocumentStorageWS1.DocumentInfo DocumentInfo;
        
        public GetDocumentTrxResponse() {
        }
        
        public GetDocumentTrxResponse(ClaimsDocsBizLogic.DocumentStorageWS1.DocumentInfo DocumentInfo) {
            this.DocumentInfo = DocumentInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateTask", WrapperNamespace="http://www.accessgeneral.com/DocumentStorage/", IsWrapped=true)]
    public partial class CreateTaskRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.accessgeneral.com/DocumentStorage/", Order=0)]
        public ClaimsDocsBizLogic.DocumentStorageWS1.DocumentInfoVar[] vars;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.accessgeneral.com/DocumentStorage/", Order=1)]
        public string docKey;
        
        public CreateTaskRequest() {
        }
        
        public CreateTaskRequest(ClaimsDocsBizLogic.DocumentStorageWS1.DocumentInfoVar[] vars, string docKey) {
            this.vars = vars;
            this.docKey = docKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateTaskResponse", WrapperNamespace="http://www.accessgeneral.com/DocumentStorage/", IsWrapped=true)]
    public partial class CreateTaskResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.accessgeneral.com/DocumentStorage/", Order=0)]
        public string CreateTaskResult;
        
        public CreateTaskResponse() {
        }
        
        public CreateTaskResponse(string CreateTaskResult) {
            this.CreateTaskResult = CreateTaskResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateTaskTrx", WrapperNamespace="http://www.accessgeneral.com/DocumentStorage/", IsWrapped=true)]
    public partial class CreateTaskTrxRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.accessgeneral.com/DocumentStorage/", Order=0)]
        public System.Guid transactionID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.accessgeneral.com/DocumentStorage/", Order=1)]
        public ClaimsDocsBizLogic.DocumentStorageWS1.DocumentInfoVar[] vars;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.accessgeneral.com/DocumentStorage/", Order=2)]
        public string docKey;
        
        public CreateTaskTrxRequest() {
        }
        
        public CreateTaskTrxRequest(System.Guid transactionID, ClaimsDocsBizLogic.DocumentStorageWS1.DocumentInfoVar[] vars, string docKey) {
            this.transactionID = transactionID;
            this.vars = vars;
            this.docKey = docKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateTaskTrxResponse", WrapperNamespace="http://www.accessgeneral.com/DocumentStorage/", IsWrapped=true)]
    public partial class CreateTaskTrxResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.accessgeneral.com/DocumentStorage/", Order=0)]
        public string CreateTaskTrxResult;
        
        public CreateTaskTrxResponse() {
        }
        
        public CreateTaskTrxResponse(string CreateTaskTrxResult) {
            this.CreateTaskTrxResult = CreateTaskTrxResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindDocument", WrapperNamespace="http://www.accessgeneral.com/DocumentStorage/", IsWrapped=true)]
    public partial class FindDocumentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.accessgeneral.com/DocumentStorage/", Order=0)]
        public System.Guid transactionID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.accessgeneral.com/DocumentStorage/", Order=1)]
        public ClaimsDocsBizLogic.DocumentStorageWS1.DocumentInfoVar[] vars;
        
        public FindDocumentRequest() {
        }
        
        public FindDocumentRequest(System.Guid transactionID, ClaimsDocsBizLogic.DocumentStorageWS1.DocumentInfoVar[] vars) {
            this.transactionID = transactionID;
            this.vars = vars;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindDocumentResponse", WrapperNamespace="http://www.accessgeneral.com/DocumentStorage/", IsWrapped=true)]
    public partial class FindDocumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.accessgeneral.com/DocumentStorage/", Order=0)]
        public ClaimsDocsBizLogic.DocumentStorageWS1.DocumentInfoVar[] vars;
        
        public FindDocumentResponse() {
        }
        
        public FindDocumentResponse(ClaimsDocsBizLogic.DocumentStorageWS1.DocumentInfoVar[] vars) {
            this.vars = vars;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DocumentStorageWSSoapChannel : ClaimsDocsBizLogic.DocumentStorageWS1.DocumentStorageWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DocumentStorageWSSoapClient : System.ServiceModel.ClientBase<ClaimsDocsBizLogic.DocumentStorageWS1.DocumentStorageWSSoap>, ClaimsDocsBizLogic.DocumentStorageWS1.DocumentStorageWSSoap {
        
        public DocumentStorageWSSoapClient() {
        }
        
        public DocumentStorageWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DocumentStorageWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentStorageWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentStorageWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClaimsDocsBizLogic.DocumentStorageWS1.SaveDocumentResponse SaveDocument(ClaimsDocsBizLogic.DocumentStorageWS1.SaveDocumentRequest request) {
            return base.Channel.SaveDocument(request);
        }
        
        public ClaimsDocsBizLogic.DocumentStorageWS1.SaveDocumentTrxResponse SaveDocumentTrx(ClaimsDocsBizLogic.DocumentStorageWS1.SaveDocumentTrxRequest request) {
            return base.Channel.SaveDocumentTrx(request);
        }
        
        public ClaimsDocsBizLogic.DocumentStorageWS1.SaveExceptionsResponse SaveExceptions(ClaimsDocsBizLogic.DocumentStorageWS1.SaveExceptionsRequest request) {
            return base.Channel.SaveExceptions(request);
        }
        
        public ClaimsDocsBizLogic.DocumentStorageWS1.SaveExceptionsTrxResponse SaveExceptionsTrx(ClaimsDocsBizLogic.DocumentStorageWS1.SaveExceptionsTrxRequest request) {
            return base.Channel.SaveExceptionsTrx(request);
        }
        
        public ClaimsDocsBizLogic.DocumentStorageWS1.GetDocumentResponse GetDocument(ClaimsDocsBizLogic.DocumentStorageWS1.GetDocumentRequest request) {
            return base.Channel.GetDocument(request);
        }
        
        public ClaimsDocsBizLogic.DocumentStorageWS1.GetDocumentTrxResponse GetDocumentTrx(ClaimsDocsBizLogic.DocumentStorageWS1.GetDocumentTrxRequest request) {
            return base.Channel.GetDocumentTrx(request);
        }
        
        public ClaimsDocsBizLogic.DocumentStorageWS1.CreateTaskResponse CreateTask(ClaimsDocsBizLogic.DocumentStorageWS1.CreateTaskRequest request) {
            return base.Channel.CreateTask(request);
        }
        
        public ClaimsDocsBizLogic.DocumentStorageWS1.CreateTaskTrxResponse CreateTaskTrx(ClaimsDocsBizLogic.DocumentStorageWS1.CreateTaskTrxRequest request) {
            return base.Channel.CreateTaskTrx(request);
        }
        
        public ClaimsDocsBizLogic.DocumentStorageWS1.FindDocumentResponse FindDocument(ClaimsDocsBizLogic.DocumentStorageWS1.FindDocumentRequest request) {
            return base.Channel.FindDocument(request);
        }
    }
}
